#!/usr/bin/env python3
"""
gen_wiki.py — Regenerate ALL Luna2D wiki pages from source content.

Reads:  specs/*.md, examples/*.lua, library/README.md, demos/README.md,
        tools/README.md, docs/architecture/*.md, .github/agents/,
        .github/skills/, vscode-extension/README.md
Writes: wiki/*.md  (44 pages total)

Usage:
    python tools/docs/gen_wiki.py                # regenerate all pages
    python tools/docs/gen_wiki.py --page Home    # single page by slug
    python tools/docs/gen_wiki.py --list         # list available page slugs
    python tools/docs/gen_wiki.py --dry-run      # preview without writing

Exit codes:
    0 — success
    1 — fatal error
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT    = Path(__file__).resolve().parent.parent.parent
SPECS   = ROOT / "specs"
EXAMPLES = ROOT / "examples"
LIBRARY = ROOT / "library"
DEMOS   = ROOT / "demos"
TOOLS   = ROOT / "tools"
DOCS    = ROOT / "docs"
GITHUB  = ROOT / ".github"
VSEXT   = ROOT / "vscode-extension"
WIKI    = ROOT / "wiki"

GEN_DATE = datetime.now(timezone.utc).strftime("%Y-%m-%d")
GEN_BANNER = (
    f"<!-- Auto-generated by tools/docs/gen_wiki.py on {GEN_DATE} — "
    "do not edit by hand. Regenerate: python tools/docs/gen_wiki.py -->\n\n"
)

# ── Utility ───────────────────────────────────────────────────────────────────

def _read(path: Path) -> str:
    """Read a file; return empty string if missing."""
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _section(text: str, name: str) -> str:
    """Extract content under '## name' heading up to the next '##' or EOF."""
    pat = rf"(?m)^## {re.escape(name)}\n(.*?)(?=^##|\Z)"
    m = re.search(pat, text, re.DOTALL)
    return m.group(1).strip() if m else ""


def _prop(text: str, key: str) -> str:
    """Extract value from '| **key** | value |' metadata table row."""
    pat = rf"\*\*{re.escape(key)}\*\*\s*\|\s*(.+?)\s*(?:\||\n)"
    m = re.search(pat, text)
    return m.group(1).strip() if m else ""


def read_spec(module: str) -> dict:
    """Read a spec file and return parsed metadata dict."""
    text = _read(SPECS / f"{module}.md")
    if not text:
        return {}
    return {
        "raw":     text,
        "tier":    _prop(text, "Tier"),
        "status":  _prop(text, "Status"),
        "api":     _prop(text, "Lua API"),
        "source":  _prop(text, "Source"),
        "summary": _section(text, "Summary"),
        "arch":    _section(text, "Architecture"),
    }


def _spec_summary(module: str, n_paragraphs: int = 2) -> str:
    """Return first n_paragraphs of spec Summary, no code blocks."""
    spec = read_spec(module)
    text = spec.get("summary", "")
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    return "\n\n".join(paras[:n_paragraphs])


def read_example(module: str, max_lines: int = 90) -> str:
    """Read an example file, stripping the boilerplate header comment."""
    text = _read(EXAMPLES / f"{module}.lua")
    if not text:
        return ""
    lines = text.split("\n")
    # Skip leading comment header lines
    cut = 0
    for i, ln in enumerate(lines[:8]):
        if re.match(r"^-- (examples/|Luna2D\b)", ln):
            cut = i + 1
    return "\n".join(lines[cut:max_lines]).strip()


def write_page(filename: str, content: str, dry_run: bool = False) -> None:
    path = WIKI / filename
    if dry_run:
        print(f"\n{'='*60}\n{filename}\n{'='*60}")
        print(content[:800])
        print("  [... truncated ...]")
        return
    path.write_text(content, encoding="utf-8")
    print(f"  wrote  wiki/{filename}")


# ── Per-module see-also map ────────────────────────────────────────────────────

_SEE_ALSO: dict[str, list[str]] = {
    "graphics":   ["Shader-Patterns", "Camera-API", "Particle-API",
                   "FX-API", "Animation-API"],
    "audio":      ["Event-API"],
    "physics":    ["Math-API", "Entity-API"],
    "input":      ["Event-API", "Window-API"],
    "math":       ["Physics-API", "Animation-API"],
    "timer":      ["Callbacks"],
    "window":     ["Configuration", "Input-API"],
    "filesystem": ["Savegame-API", "Modding-API"],
    "entity":     ["Scene-API", "Physics-API"],
    "scene":      ["Entity-API", "Tilemap-API", "Camera-API"],
    "tilemap":    ["Pathfinding-API", "Scene-API", "Procgen-API"],
    "pathfinding":["AI-API", "Tilemap-API"],
    "ai":         ["Pathfinding-API", "Entity-API"],
    "thread":     ["Event-API", "Network-API"],
    "particle":   ["Graphics-API", "FX-API"],
    "animation":  ["Graphics-API", "Tilemap-API"],
    "camera":     ["Graphics-API", "Scene-API"],
    "gui":        ["Terminal-API", "Event-API"],
    "terminal":   ["GUI-API"],
    "fx":         ["Graphics-API", "Shader-Patterns"],
    "pipeline":   ["Graphics-API", "FX-API"],
    "event":      ["Threading", "Automation-API"],
    "automation": ["Event-API"],
    "data":       ["Data-APIs", "Filesystem-API"],
    "dataframe":  ["Data-APIs"],
    "compute":    ["Data-APIs"],
    "graph":      ["Data-APIs", "Pathfinding-API"],
    "serial":     ["Data-APIs", "Filesystem-API"],
    "image":      ["Graphics-API"],
    "network":    ["Threading", "Filesystem-API"],
    "savegame":   ["Filesystem-API", "Data-APIs"],
    "modding":    ["Filesystem-API", "Lunasome"],
    "minimap":    ["Tilemap-API", "Camera-API"],
    "light":      ["Graphics-API", "Shader-Patterns"],
    "procgen":    ["Tilemap-API", "Math-API"],
    "raycaster":  ["Physics-API", "Tilemap-API"],
    "spine":      ["Animation-API", "Graphics-API"],
}


# ── Generic module API page ────────────────────────────────────────────────────

def gen_module_page(
    module: str,
    wiki_title: str,
    n_summary_paras: int = 2,
    example_max_lines: int = 90,
    extra_sections: str = "",
    see_also_override: list | None = None,
) -> str:
    spec = read_spec(module)
    if not spec:
        return (
            GEN_BANNER
            + f"# {wiki_title}\n\n"
            + f"> Specification not found for module `{module}`. "
            + "Check `specs/{module}.md`.\n"
        )

    tier    = spec.get("tier", "")
    status  = spec.get("status", "")
    api_ns  = spec.get("api",    f"luna.{module}")
    source  = spec.get("source", f"src/{module}/")
    tier_short = re.sub(r" — .*", "", tier)

    overview = _spec_summary(module, n_summary_paras)
    example  = read_example(module, example_max_lines)

    see_pages = see_also_override or _SEE_ALSO.get(module, [])
    see_links  = " · ".join(f"[[{p}]]" for p in see_pages)
    if see_links:
        see_links += " · "
    see_links += "[[API-Reference]]"

    parts = [
        GEN_BANNER,
        f"# {wiki_title}",
        "",
        f"> *{tier_short} · Lua API: `{api_ns}` · Source: `{source}` · {status}*",
        "",
        "---",
        "",
        "## Overview",
        "",
        overview,
        "",
    ]

    if example:
        parts += [
            "---",
            "",
            "## Example",
            "",
            "```lua",
            example,
            "```",
            "",
        ]

    if extra_sections:
        parts += [
            "---",
            "",
            extra_sections.strip(),
            "",
        ]

    parts += [
        "---",
        "",
        "## See Also",
        "",
        see_links,
    ]

    return "\n".join(parts)


# ═══════════════════════════════════════════════════════════════════════════════
# Special-page generators
# ═══════════════════════════════════════════════════════════════════════════════

def gen_home() -> str:
    return GEN_BANNER + dedent("""\
    # Luna2D — Wiki

    > **Luna2D** is a 2D game engine written in Rust that loads and executes Lua game scripts.
    > Single binary · Desktop-first · LuaJIT · wgpu 22 · rapier2d 0.32 · rodio 0.17

    ---

    ## Quick Start

    ```powershell
    git clone https://github.com/RandomBladeDude/luna2d
    cd luna2d
    cargo build --release
    cargo run -- demos/showcase/hello_world
    ```

    Minimal `main.lua`:

    ```lua
    function luna.load()
        luna.window.setTitle("My Game")
        luna.graphics.setBackgroundColor(0.1, 0.1, 0.2)
    end

    function luna.update(dt)
        -- game logic: move objects, run physics, etc.
    end

    function luna.draw()
        luna.graphics.setColor(1, 1, 1)
        luna.graphics.print("Hello, Luna2D!", 300, 280, 3)
    end
    ```

    ---

    ## Navigation

    ### Getting Started
    | Page | What it covers |
    |------|----------------|
    | [[Getting-Started]] | Installation, first game, project layout |
    | [[Configuration]] | `conf.lua` / `conf.toml` — window and module settings |
    | [[Callbacks]] | All engine callbacks (`luna.load`, `luna.update`, `luna.draw`, …) |
    | [[Examples]] | 38 single-file API usage scripts |
    | [[Demos]] | 111+ playable demos organised by genre |

    ### Engine Architecture
    | Page | What it covers |
    |------|----------------|
    | [[Architecture]] | Module tiers, boot sequence, shared state, dependency graph |
    | [[Design-Principles]] | The Zen of Luna — binding constraints and first principles |

    ### Core API Reference
    | Page | What it covers |
    |------|----------------|
    | [[API-Reference]] | Full Luna2D cheatsheet — every `luna.*` function on one page |
    | [[Graphics-API]] | `luna.graphics` — drawing, images, fonts, shaders, canvas |
    | [[Audio-API]] | `luna.audio` — sources, playback, mixer, buses |
    | [[Physics-API]] | `luna.physics` — worlds, bodies, shapes, joints, raycasting |
    | [[Input-API]] | `luna.input` / keyboard / mouse / gamepad / touch |
    | [[Math-API]] | `luna.math` — vectors, random, noise, transforms |
    | [[Timer-API]] | `luna.timer` — delta time, FPS, sleep, scheduler |
    | [[Filesystem-API]] | `luna.filesystem` — sandboxed I/O, virtual FS |
    | [[Window-API]] | `luna.window` — fullscreen, DPI, clipboard |

    ### Graphics & Rendering
    | Page | What it covers |
    |------|----------------|
    | [[Camera-API]] | `luna.camera` — viewport transforms, zoom, shake |
    | [[Animation-API]] | `luna.animation` — sprite-sheet frame animation |
    | [[Particle-API]] | `luna.particle` — emitters, modifiers, keyframe |
    | [[FX-API]] | `luna.fx` / `luna.pipeline` — post-processing, render pipeline |
    | [[Shader-Patterns]] | Custom WGSL shaders with `luna.graphics.newShader` |

    ### Game Systems
    | Page | What it covers |
    |------|----------------|
    | [[Tilemap-API]] | `luna.tilemap` — tiles, layers, auto-tile, isometric/hex |
    | [[Scene-API]] | `luna.scene` — scene stack, transitions, depth sorting |
    | [[Entity-API]] | `luna.entity` — ECS, components, tags, systems |
    | [[Pathfinding-API]] | `luna.pathfinding` — NavGrid, A\\*, flow fields |
    | [[AI-API]] | `luna.ai` — FSM, behaviour trees, steering, GOAP, Q-learning |
    | [[Savegame-API]] | `luna.savegame` — save/load slots, versioned tables |

    ### UI & Terminal
    | Page | What it covers |
    |------|----------------|
    | [[GUI-API]] | `luna.gui` — retained-mode widget system, 32 widget types |
    | [[Terminal-API]] | `luna.terminal` — grid-based character terminal emulator |

    ### Data & Scripting
    | Page | What it covers |
    |------|----------------|
    | [[Data-APIs]] | `luna.data` / compute / dataframe / graph / serial / image |
    | [[Event-API]] | `luna.event` — event queue and pub/sub |
    | [[Threading]] | `luna.thread` — worker threads, channels |
    | [[Automation-API]] | `luna.automation` — scripted sequences and macros |
    | [[Network-API]] | `luna.network` — TCP/UDP client-server, HTTP client |

    ### Effects & Extras
    | Page | What it covers |
    |------|----------------|
    | [[Modding-API]] | `luna.modding` — mod loading, hot-reload |
    | [[Procgen-API]] | `luna.procgen` — map generators, noise, cellular automata |
    | [[Advanced-APIs]] | Raycaster, Spine, Light, Minimap |

    ### Standard Library (Lunasome)
    | Page | What it covers |
    |------|----------------|
    | [[Lunasome]] | Pure-Lua game systems: dialog, inventory, crafting, quest, battle … |

    ### Tooling
    | Page | What it covers |
    |------|----------------|
    | [[VS-Code-Extension]] | IntelliSense, MCP server, debugger, completions |
    | [[Tools]] | CLI scripts — docs, audit, validate, dist, github |
    | [[CAG-System]] | Copilot Agent system — agents, skills, prompts |

    ---

    ## Engine at a Glance

    | Layer | Modules |
    |-------|---------|
    | **Baseline** | `math` |
    | **Tier 1** | `graphics` · `audio` · `physics` · `input` · `timer` · `window` · `filesystem` · `entity` · `event` · `image` · `data` · `thread` · `camera` · `animation` · `automation` · `compute` · `sound` |
    | **Tier 2** | `gui` · `scene` · `tilemap` · `particle` · `pathfinding` · `ai` · `fx` · `pipeline` · `terminal` · `minimap` · `modding` · `network` · `savegame` · `dataframe` · `graph` · `serial` · `spine` · `light` · `raycaster` · `procgen` |
    | **Bridge** | `lua_api` — registers every `luna.*` binding |
    | **Tier 3** | `library/` — Lunasome pure-Lua game libraries |
    | **Games** | `demos/` · user `main.lua` |

    ---

    *Rust 1.78+ · LuaJIT via mlua 0.9 · wgpu 22 · winit 0.30 · rapier2d 0.32 · rodio 0.17 · MIT License*
    """)


def gen_getting_started() -> str:
    text = _read(WIKI / "Getting-Started.md")
    if text and not text.startswith("<!--"):
        # Already good — just add banner if missing
        return GEN_BANNER + text
    return GEN_BANNER + dedent("""\
    # Getting Started

    ## Prerequisites

    - Rust stable ≥ 1.78 (install via [rustup](https://rustup.rs))
    - A C compiler for LuaJIT vendored build: MSVC on Windows, GCC/Clang on Linux/macOS

    ## Build

    ```powershell
    git clone https://github.com/RandomBladeDude/luna2d
    cd luna2d
    cargo build --release
    ```

    The binary is at `build/release/luna2d.exe` (Windows) or `build/release/luna2d` (Linux/macOS).

    ## Install Locally (optional)

    ```powershell
    # Windows
    powershell tools/dist/install.ps1

    # Linux / macOS
    bash tools/dist/install.sh
    ```

    ---

    ## Your First Game

    ### Minimal project layout

    ```
    my_game/
    └── main.lua
    ```

    ### Minimal main.lua

    ```lua
    function luna.load()
        luna.window.setTitle("My Game")
        luna.graphics.setBackgroundColor(0.1, 0.1, 0.2)
    end

    function luna.update(dt)
        -- game logic here
    end

    function luna.draw()
        luna.graphics.setColor(1, 1, 1)
        luna.graphics.print("Hello, Luna2D!", 300, 280, 3)
    end
    ```

    ### Run it

    ```bash
    luna2d path/to/my_game
    # or during development:
    cargo run -- path/to/my_game
    ```

    ---

    ## Adding a Config File (optional)

    Create `conf.lua` in your game folder to configure the window before it opens:

    ```lua
    function luna.conf(t)
        t.window.title  = "My Game"
        t.window.width  = 1280
        t.window.height = 720
        t.window.vsync  = true
        t.identity      = "my_game"   -- save directory name
    end
    ```

    See [[Configuration]] for the full list of options.

    ---

    ## Running the Demos

    Luna2D ships with 111+ playable demos:

    ```bash
    cargo run -- demos/arcade/pong
    cargo run -- demos/showcase/hello_world
    cargo run -- demos/simulation/physics_demo
    ```

    See [[Demos]] for the full index.

    ---

    ## Running Examples

    Single-file API usage scripts are in `examples/`:

    ```bash
    cargo run -- examples/physics.lua
    cargo run -- examples/tilemap.lua
    ```

    See [[Examples]] for all 38 examples.

    ---

    ## Next Steps

    | Topic | Page |
    |-------|------|
    | Callbacks reference | [[Callbacks]] |
    | Full API cheatsheet | [[API-Reference]] |
    | Graphics API | [[Graphics-API]] |
    | Physics API | [[Physics-API]] |
    | Standard library | [[Lunasome]] |
    | VS Code extension | [[VS-Code-Extension]] |
    """)


def gen_architecture() -> str:
    # Read the authoritative docs/architecture/engine-architecture.md
    arch_text = _read(DOCS / "architecture" / "engine-architecture.md")
    if not arch_text:
        arch_text = _read(WIKI / "Architecture.md").replace("<!-- Auto-generated", "")

    # Replace plain .md references with wiki links where appropriate
    arch_text = re.sub(
        r'\[([^\]]+)\]\(philosophy\.md\)',
        r'[[\1|Design-Principles]]',
        arch_text,
    )
    arch_text = re.sub(
        r'\[([^\]]+)\]\(test-framework\.md\)',
        r'[[\1|Architecture]]',
        arch_text,
    )

    return GEN_BANNER + f"# Luna2D Architecture\n\n{arch_text.strip()}\n"


def gen_design_principles() -> str:
    phil_text = _read(DOCS / "architecture" / "philosophy.md")
    if not phil_text:
        phil_text = _read(WIKI / "Design-Principles.md")

    return GEN_BANNER + f"# Design Principles\n\n{phil_text.strip()}\n"


def gen_configuration() -> str:
    existing = _read(WIKI / "Configuration.md")
    if existing and not existing.startswith("<!--"):
        return GEN_BANNER + existing
    return GEN_BANNER + dedent("""\
    # Configuration

    Luna2D reads configuration from two optional files before any game code runs.

    ---

    ## conf.lua

    Place `conf.lua` in your game folder alongside `main.lua`.
    The `luna.conf(t)` callback is called during engine boot — before the window is opened.

    ```lua
    function luna.conf(t)
        -- Window
        t.window.title      = "My Game"
        t.window.width      = 1280
        t.window.height     = 720
        t.window.fullscreen = false
        t.window.resizable  = true
        t.window.vsync      = true
        t.window.fps_cap    = 0      -- 0 = no cap

        -- Identity (used for save directory)
        t.identity = "my_game"

        -- Modules (set false to disable)
        t.modules.physics   = true
        t.modules.audio     = true
        t.modules.gui       = true
        t.modules.terminal  = true
        t.modules.network   = false
        t.modules.modding   = false

        -- Debug
        t.debug.show_fps    = false
    end
    ```

    ---

    ## conf.toml

    Alternatively, use a `conf.toml` file (TOML format) for the same settings:

    ```toml
    [window]
    title      = "My Game"
    width      = 1280
    height     = 720
    fullscreen = false
    vsync      = true

    [modules]
    physics = true
    audio   = true
    ```

    Both formats are equivalent. `conf.lua` takes precedence if both exist.

    ---

    ## Config Fields Reference

    | Field | Type | Default | Description |
    |-------|------|---------|-------------|
    | `window.title` | string | `"Luna2D"` | Window title bar text |
    | `window.width` | int | `1280` | Initial window width in pixels |
    | `window.height` | int | `720` | Initial window height in pixels |
    | `window.fullscreen` | bool | `false` | Start in fullscreen |
    | `window.resizable` | bool | `true` | Allow window resize |
    | `window.vsync` | bool | `true` | Enable vertical sync |
    | `window.fps_cap` | int | `0` | Max FPS (0 = unlimited) |
    | `identity` | string | `""` | App identity for save directory |
    | `modules.physics` | bool | `true` | Enable physics module |
    | `modules.audio` | bool | `true` | Enable audio module |
    | `modules.gui` | bool | `true` | Enable GUI module |
    | `modules.terminal` | bool | `true` | Enable terminal module |
    | `modules.network` | bool | `false` | Enable network module |
    | `modules.modding` | bool | `false` | Enable modding module |
    | `debug.show_fps` | bool | `false` | Show FPS counter overlay |

    ---

    See also: [[Getting-Started]] · [[Callbacks]] · [[Window-API]]
    """)


def gen_callbacks() -> str:
    existing = _read(WIKI / "Callbacks.md")
    if existing and not existing.startswith("<!--"):
        return GEN_BANNER + existing
    return GEN_BANNER + dedent("""\
    # Callbacks

    All engine callbacks are defined as global functions in `main.lua`. Every callback is optional — a blank `main.lua` is valid.

    ---

    ## Core Loop

    ```lua
    function luna.conf(t)       end  -- called before window opens; configure in conf.lua
    function luna.load()        end  -- called once after script and assets are loaded
    function luna.update(dt)    end  -- dt: seconds; called every frame before draw
    function luna.draw()        end  -- called every frame; push draw commands here
    function luna.quit()        end  -- called before the engine exits; return true to cancel
    ```

    ---

    ## Keyboard

    ```lua
    function luna.keypressed(key, scancode, isrepeat)  end  -- key: string; isrepeat: bool
    function luna.keyreleased(key, scancode)           end
    function luna.textinput(text)                      end  -- Unicode character input
    ```

    ---

    ## Mouse

    ```lua
    function luna.mousepressed(x, y, button)           end  -- button: 1=left 2=right 3=middle
    function luna.mousereleased(x, y, button)          end
    function luna.mousemoved(x, y, dx, dy)             end
    function luna.wheelmoved(x, y)                     end  -- scroll delta
    ```

    ---

    ## Gamepad

    ```lua
    function luna.gamepadpressed(id, button)           end  -- id: number; button: string
    function luna.gamepadreleased(id, button)          end
    function luna.gamepadaxis(id, axis, value)         end  -- value: -1.0..1.0
    function luna.joystickadded(id)                    end  -- device connected
    function luna.joystickremoved(id)                  end  -- device disconnected
    ```

    ---

    ## Touch

    ```lua
    function luna.touchpressed(id, x, y, dx, dy, pressure)   end
    function luna.touchmoved(id, x, y, dx, dy, pressure)     end
    function luna.touchreleased(id, x, y, dx, dy, pressure)  end
    ```

    ---

    ## Window

    ```lua
    function luna.focus(focused)    end  -- focused: bool; window focus changed
    function luna.visible(visible)  end  -- visible: bool; window hidden or shown
    function luna.resize(w, h)      end  -- new window dimensions
    ```

    ---

    ## Callback Execution Order

    ```
    luna.conf(t)          ← before window opens (from conf.lua)
    window opens
    luna.load()           ← once, after full init
    ┌─ frame loop ──────────────────────────────
    │  poll events → fire luna.key*/mouse*/etc.
    │  luna.update(dt)
    │  luna.draw()        ← push DrawCommands
    │  GpuRenderer renders the command queue
    └────────────────────────────────────────────
    luna.quit()           ← on window close
    ```

    ---

    See also: [[Getting-Started]] · [[Timer-API]] · [[Input-API]]
    """)


def gen_examples() -> str:
    """List all 38 examples with brief descriptions."""
    ex_dir = EXAMPLES
    files = sorted(ex_dir.glob("*.lua"))

    rows = []
    for f in files:
        name = f.stem
        # Try to get module from first non-blank comment line
        text = _read(f)
        lines = text.split("\n")
        desc = ""
        for ln in lines[:6]:
            ln = ln.strip()
            if ln.startswith("-- ") and not ln.startswith("-- examples/") and not ln.startswith("-- Luna2D "):
                desc = ln[3:].strip()
                break
        if not desc:
            desc = f"Usage examples for `luna.{name}`"
        rows.append(f"| `examples/{name}.lua` | {desc} |")

    table = "\n".join(rows)
    return GEN_BANNER + dedent(f"""\
    # Examples

    Single-file API usage scripts — each demonstrates one `luna.*` namespace.
    These are documentation code, not runnable games.

    ## Running an Example

    ```bash
    cargo run -- examples/timer.lua
    cargo run -- examples/physics.lua
    # etc.
    ```

    Or with the installed binary:
    ```bash
    luna examples/timer.lua
    ```

    ---

    ## Example Index

    | File | Description |
    |------|-------------|
    {table}

    ---

    For complete runnable games, see [[Demos]].
    For the full API reference, see [[API-Reference]].
    """)


def gen_demos() -> str:
    """Generate Demos.md from demos/README.md."""
    demos_readme = _read(DEMOS / "README.md")
    if demos_readme:
        return GEN_BANNER + f"# Demos\n\n{demos_readme.strip()}\n"
    return GEN_BANNER + dedent("""\
    # Demos

    Luna2D ships with 111+ fully playable demo games, organised by genre.
    Run any demo with:

    ```bash
    cargo run -- demos/<category>/<name>
    luna demos/<category>/<name>
    ```

    ## Genres

    | Category | Demo Count | Examples |
    |----------|-----------|---------|
    | `arcade/` | 10 | pong, tetris, pac_man, snake, space_invaders |
    | `action/` | 14 | platformer, roguelite, bullet_hell, metroidvania |
    | `rpg/` | 12 | roguelike, visual_novel, survival_crafting |
    | `simulation/` | 17 | physics_demo, factory, farming_sim, god_game |
    | `strategy/` | 13 | tower_defense, card_game, rts, hex_strategy |
    | `sports/` | 11 | golf_classic, pinball, rhythm_game |
    | `retro/` | 10 | boulder_dash, turrican, lemmings |
    | `showcase/` | 24 | hello_world, particles_demo, postfx_demo |

    See [[Examples]] for single-file API usage scripts instead.
    """)


def gen_lunasome() -> str:
    """Generate Lunasome.md from library/ content."""
    lib_readme = _read(LIBRARY / "README.md")
    # Clean up box-drawing artefacts from the readme
    lib_readme = lib_readme.replace("ÔÇö", "—").replace("Ôťů", "✔").replace("­čöž", "🔧")

    module_rows = []
    for subdir in sorted(LIBRARY.iterdir()):
        if not subdir.is_dir():
            continue
        agent_md = _read(subdir / "AGENT.md")
        summary = ""
        if agent_md:
            # Get first non-empty line after the heading
            for ln in agent_md.split("\n")[1:]:
                ln = ln.strip()
                if ln and not ln.startswith("#") and not ln.startswith("|"):
                    summary = ln[:100]
                    break
        if not summary:
            summary = f"`library.{subdir.name}`"
        module_rows.append(
            f"| `library.{subdir.name}` | {summary} |"
        )

    rows_str = "\n".join(module_rows)

    return GEN_BANNER + dedent(f"""\
    # Lunasome — Standard Library

    Tier 3 pure-Lua gameplay libraries that ship alongside Luna2D but are not embedded in the binary.
    They consume only the public `luna.*` API — no Rust engine internals.

    ## Using Lunasome

    ```lua
    local dialog    = require("library.dialog")
    local inventory = require("library.inventory")
    local quest     = require("library.quest")
    ```

    The engine automatically adds the `library/` search path when a game is loaded.

    ---

    ## Module Index

    | Module | Description |
    |--------|-------------|
    {rows_str}

    ---

    ## Layer Contract

    - Lunasome modules **only** import from `luna.*` and other `library.*` modules
    - The Rust engine never depends on `library/`
    - Lunasome is versioned alongside the engine

    ---

    ## Testing

    ```bash
    cargo test lua_test_library_dialog
    cargo test lua_test_library_inventory
    cargo test lua_test_library_quest
    ```

    Tests live in `tests/lua/library/`.

    ---

    See also: [[Demos]] · [[Examples]] · [[API-Reference]]

    ---

    ## Full README

    {lib_readme.strip()}
    """)


def gen_tools() -> str:
    """Generate Tools.md from tools/README.md + subfolder info."""
    tools_readme = _read(TOOLS / "README.md")
    return GEN_BANNER + dedent(f"""\
    # Tools

    Permanent CLI scripts for the Luna2D engine pipeline, organised under `tools/`.

    Each subfolder has its own `README.md` with the full script list and usage examples.

    ---

    ## Policy

    | Location | For |
    |---|---|
    | `tools/<category>/` | Permanent CLI utilities — reusable by any agent, CI, or developer |
    | `work/{{session}}/scripts/` | Session-scoped scripts — archived after the session |

    **Never** create one-off scripts in `tools/`. They go in `work/{{session}}/scripts/`.

    ---

    ## Quick Reference

    ### Documentation

    ```powershell
    python tools/docs/gen_wiki.py                      # Regenerate ALL wiki pages
    python tools/docs/gen_wiki_api.py                  # Regenerate API-Reference.md cheatsheet
    python tools/docs/gen_lua_api.py                   # Lua API reference (docs/API/lua-api.md)
    python tools/docs/collect_docs.py --report-missing # List missing docstrings (exit 1 if any)
    python tools/gen_all_docs.py                       # Full documentation pipeline
    ```

    ### Auditing & Coverage

    ```powershell
    python tools/audit/doc_coverage.py                 # Docstring coverage report
    python tools/audit/test_coverage.py                # Test coverage summary
    python tools/audit/audit_module.py <name>          # Single module audit
    python tools/audit/module_audit.py                 # Full codebase module audit
    ```

    ### Validation

    ```powershell
    python tools/validate/cag_validate.py              # Validate all .github/ CAG files
    python tools/validate/validate_lua_api.py          # Check Lua API consistency
    python tools/validate/validate_game.py             # Validate a game folder
    ```

    ### Building & Distribution

    ```powershell
    powershell tools/dist/dist.ps1                     # Package for Windows
    bash tools/dist/dist.sh                            # Package for Linux/macOS
    makensis tools/dist/installer.nsi                  # Build NSIS installer (Windows)
    ```

    ### Assets

    ```powershell
    python tools/assets/gen_splash.py                  # Regenerate splash screen PNG
    python tools/assets/gen_icon.py                    # Regenerate icon files
    ```

    ---

    ## Subfolder Index

    {tools_readme.strip()}

    ---

    See also: [[CAG-System]] · [[VS-Code-Extension]] · [[Architecture]]
    """)


def gen_cag_system() -> str:
    """Generate CAG-System.md from .github/agents/ and .github/skills/ content."""
    agents_dir = GITHUB / "agents"
    skills_dir = GITHUB / "skills"

    agent_rows = []
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*.agent.md")):
            text = _read(f)
            # Try YAML frontmatter 'description:' field first
            fm_match = re.search(
                r'^description:\s*["\']?(.*?)["\']?\s*$',
                text, re.MULTILINE,
            )
            if fm_match:
                raw = fm_match.group(1).strip().strip('"\'')
                # Strip markdown bold **Name** — prefix if present
                raw = re.sub(r'^\*\*[^*]+\*\*\s*—\s*', '', raw)
                mission = raw[:130]
            else:
                # Fall back to first line of ## Mission section
                mm = re.search(r"## Mission\s*\n(.+?)(?:\n|$)", text)
                mission = mm.group(1).strip()[:130] if mm else "—"
            name = f.stem.replace(".agent", "")
            # Use display name from frontmatter 'name:' if present
            name_match = re.search(r'^name:\s*(.+)$', text, re.MULTILINE)
            display = name_match.group(1).strip() if name_match else name
            agent_rows.append(f"| **{display}** | {mission} |")

    skill_rows = []
    if skills_dir.exists():
        for subdir in sorted(skills_dir.iterdir()):
            if not subdir.is_dir():
                continue
            skill_md = _read(subdir / "SKILL.md")
            # Get first non-heading description paragraph
            desc = ""
            for ln in skill_md.split("\n")[:20]:
                ln = ln.strip()
                if ln and not ln.startswith("#") and not ln.startswith("<!--"):
                    desc = ln[:120]
                    break
            skill_rows.append(f"| `{subdir.name}` | {desc[:120]} |")

    agent_table = "\n".join(agent_rows) if agent_rows else "_No agents found._"
    skill_table = "\n".join(skill_rows) if skill_rows else "_No skills found._"

    return GEN_BANNER + dedent(f"""\
    # CAG System — Copilot Agent Customization

    The `.github/` folder contains the Luna2D CAG (Copilot Agent Customization) layer:
    agents, skills, prompts, and the system prompt that configure GitHub Copilot
    for AI-first Luna2D development.

    ---

    ## Overview

    The CAG layer follows a strict load order:

    ```
    System Prompt (.github/copilot-instructions.md)
      └── src/<module>/AGENT.md       (module overview)
          └── specs/<module>.md       (full technical spec)
              └── Skills (on-demand)
                  └── Prompts / Agents
    ```

    ---

    ## Agents

    Specialist agents, each with a defined mission and skill set:

    | Agent | Mission |
    |-------|---------|
    {agent_table}

    ---

    ## Skills

    Domain-specific skill files loaded when a matching task is detected:

    | Skill | Description |
    |-------|-------------|
    {skill_table}

    ---

    ## Validation

    After editing any `.github/` file, run:

    ```powershell
    python tools/validate/cag_validate.py              # Full validation
    python tools/validate/cag_validate.py --file <path>  # Single file
    ```

    Exit code 1 = validation failed.

    ---

    ## Session Workflow

    Every agent session must:
    1. Confirm branch: `git rev-parse --abbrev-ref HEAD` → `work/branch.txt`
    2. Create `work/{{session-name}}/` with 8 subfolders
    3. Create `work/{{session-name}}/logs/agent_log.jsonl`
    4. Route to `Planner` for tasks spanning 3+ agents or 5+ files

    ---

    See also: [[Tools]] · [[VS-Code-Extension]] · [[Architecture]]
    """)


def gen_vscode_ext() -> str:
    ext_readme = _read(VSEXT / "README.md")
    existing_wiki = _read(WIKI / "VS-Code-Extension.md")

    if existing_wiki and not existing_wiki.startswith("<!--"):
        base = existing_wiki
    elif ext_readme:
        base = ext_readme
    else:
        base = "See the `vscode-extension/` folder for source."

    return GEN_BANNER + f"# VS Code Extension\n\n{base.strip()}\n\n---\n\nSee also: [[CAG-System]] · [[Tools]]"


def gen_shader_patterns() -> str:
    existing = _read(WIKI / "Shader-Patterns.md")
    if existing and not existing.startswith("<!--"):
        return GEN_BANNER + existing
    return GEN_BANNER + dedent("""\
    # Shader Patterns

    Luna2D supports custom WGSL shaders via `luna.graphics.newShader`.

    ---

    ## Creating a Shader

    ```lua
    local shader = luna.graphics.newShader([[
        @group(0) @binding(0) var tex: texture_2d<f32>;
        @group(0) @binding(1) var samp: sampler;

        struct VertexOut {
            @builtin(position) pos : vec4<f32>,
            @location(0) uv : vec2<f32>,
        };

        @fragment
        fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
            let col = textureSample(tex, samp, in.uv);
            return vec4(1.0 - col.r, 1.0 - col.g, 1.0 - col.b, col.a);  // invert
        }
    ]])
    ```

    ---

    ## Applying a Shader

    ```lua
    function luna.draw()
        luna.graphics.setShader(shader)
        luna.graphics.draw(image, 0, 0)
        luna.graphics.setShader()  -- reset to default
    end
    ```

    ---

    ## Shader Uniforms

    ```lua
    shader:send("time", luna.timer.getTime())
    shader:send("resolution", {1280, 720})
    ```

    ---

    ## Post-Processing Shaders

    For screen-space effects, use `luna.fx` with a canvas:

    ```lua
    local canvas = luna.graphics.newCanvas(1280, 720)
    local blur   = luna.fx.newEffect("blur", { radius = 4 })

    function luna.draw()
        luna.graphics.setCanvas(canvas)
        -- draw scene ...
        luna.graphics.setCanvas()

        luna.fx.apply(blur, canvas)
        luna.graphics.draw(canvas, 0, 0)
    end
    ```

    ---

    See also: [[Graphics-API]] · [[FX-API]] · [[Camera-API]]
    """)


def gen_data_apis() -> str:
    """Combined page for data, dataframe, compute, graph, serial, image."""
    sections = []
    for module, title in [
        ("data",      "luna.data — Data Utilities"),
        ("dataframe", "luna.dataframe — DataFrame"),
        ("compute",   "luna.compute — NdArray Compute"),
        ("graph",     "luna.graph — Graph"),
        ("serial",    "luna.serial — Serialization"),
        ("image",     "luna.image — CPU Image"),
    ]:
        spec = read_spec(module)
        summary = _spec_summary(module, 1)
        example = read_example(module, 50)
        tier_short = re.sub(r" — .*", "", spec.get("tier", "")) if spec else ""
        api_ns = spec.get("api", f"luna.{module}") if spec else f"luna.{module}"

        section = [f"## {title}", ""]
        if tier_short:
            section.append(f"> *{tier_short} · `{api_ns}`*")
            section.append("")
        if summary:
            section.append(summary)
            section.append("")
        if example:
            section += ["```lua", example, "```", ""]
        sections.append("\n".join(section))

    body = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Data APIs

    Luna2D provides a comprehensive suite of data processing modules for games that need
    structured data, numerical computation, graph algorithms, and serialisation.

    ---

    {body}

    ---

    See also: [[Filesystem-API]] · [[Savegame-API]] · [[Network-API]] · [[API-Reference]]
    """)


def gen_fx_api() -> str:
    """Combined page for fx and pipeline."""
    fx_overview = _spec_summary("fx", 2)
    fx_example  = read_example("fx", 70)
    pip_overview = _spec_summary("pipeline", 2)
    pip_example  = read_example("pipeline", 70)

    return GEN_BANNER + dedent(f"""\
    # FX & Pipeline API

    Post-processing effects and multi-pass render pipeline.

    ---

    ## luna.fx — Post-Processing Effects

    {fx_overview}

    ```lua
    {fx_example}
    ```

    ---

    ## luna.pipeline — Render Pipeline Control

    {pip_overview}

    ```lua
    {pip_example}
    ```

    ---

    See also: [[Graphics-API]] · [[Shader-Patterns]] · [[Camera-API]] · [[API-Reference]]
    """)


def gen_advanced_apis() -> str:
    """Page for raycaster, spine, light, minimap — modules without dedicated pages."""
    sections = []
    for module, title in [
        ("raycaster", "luna.raycaster — 3D-style Raycasting"),
        ("light",     "luna.light — Dynamic 2D Lighting"),
        ("minimap",   "luna.minimap — Minimap Renderer"),
        ("spine",     "luna.spine — Spine Skeletal Animation"),
        ("procgen",   "luna.procgen — Procedural Generation"),
    ]:
        summary = _spec_summary(module, 1)
        example = read_example(module, 50)
        spec = read_spec(module)
        api_ns = spec.get("api", f"luna.{module}") if spec else f"luna.{module}"
        section = [f"## {title}", "", f"> *`{api_ns}`*", ""]
        if summary:
            section += [summary, ""]
        if example:
            section += ["```lua", example, "```", ""]
        sections.append("\n".join(section))

    body = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Advanced APIs

    Specialised modules for visual effects, procedural generation, and advanced rendering.

    ---

    {body}

    ---

    See also: [[Graphics-API]] · [[Tilemap-API]] · [[Shader-Patterns]] · [[Procgen-API]] · [[API-Reference]]
    """)


def gen_sidebar() -> str:
    return dedent("""\
    ## Luna2D Wiki

    ### Getting Started
    * [[Home]]
    * [[Getting-Started]]
    * [[Configuration]]
    * [[Callbacks]]
    * [[Examples]]
    * [[Demos]]

    ### Architecture
    * [[Architecture]]
    * [[Design-Principles]]

    ### API Reference
    * [[API-Reference]]

    ### Core Modules
    * [[Graphics-API]]
    * [[Audio-API]]
    * [[Physics-API]]
    * [[Input-API]]
    * [[Math-API]]
    * [[Timer-API]]
    * [[Filesystem-API]]
    * [[Window-API]]

    ### Graphics & Rendering
    * [[Camera-API]]
    * [[Animation-API]]
    * [[Particle-API]]
    * [[FX-API]]
    * [[Shader-Patterns]]

    ### Game Systems
    * [[Tilemap-API]]
    * [[Scene-API]]
    * [[Entity-API]]
    * [[Pathfinding-API]]
    * [[AI-API]]
    * [[Savegame-API]]

    ### UI
    * [[GUI-API]]
    * [[Terminal-API]]

    ### Data & Scripting
    * [[Data-APIs]]
    * [[Event-API]]
    * [[Automation-API]]
    * [[Threading]]
    * [[Network-API]]

    ### Effects & Extras
    * [[Modding-API]]
    * [[Procgen-API]]
    * [[Advanced-APIs]]

    ### Standard Library
    * [[Lunasome]]

    ### Tooling
    * [[VS-Code-Extension]]
    * [[Tools]]
    * [[CAG-System]]
    """)


def gen_footer() -> str:
    return "---\n[Luna2D](https://github.com/RandomBladeDude/luna2d) · MIT License · Built with Rust + LuaJIT\n"


# ═══════════════════════════════════════════════════════════════════════════════
# Page registry
# ═══════════════════════════════════════════════════════════════════════════════

PAGES: dict[str, tuple[str, callable]] = {
    "Home":              ("Home.md",              gen_home),
    "Getting-Started":   ("Getting-Started.md",   gen_getting_started),
    "Architecture":      ("Architecture.md",       gen_architecture),
    "Design-Principles": ("Design-Principles.md",  gen_design_principles),
    "Configuration":     ("Configuration.md",      gen_configuration),
    "Callbacks":         ("Callbacks.md",          gen_callbacks),
    "Examples":          ("Examples.md",           gen_examples),
    "Demos":             ("Demos.md",              gen_demos),
    "Lunasome":          ("Lunasome.md",           gen_lunasome),
    "Tools":             ("Tools.md",              gen_tools),
    "CAG-System":        ("CAG-System.md",         gen_cag_system),
    "VS-Code-Extension": ("VS-Code-Extension.md",  gen_vscode_ext),
    "Shader-Patterns":   ("Shader-Patterns.md",    gen_shader_patterns),
    "Data-APIs":         ("Data-APIs.md",          gen_data_apis),
    "FX-API":            ("FX-API.md",             gen_fx_api),
    "Advanced-APIs":     ("Advanced-APIs.md",      gen_advanced_apis),
    # ── Module API pages ──────────────────────────────────────────────
    "Graphics-API":      ("Graphics-API.md",
                          lambda: gen_module_page("graphics", "Graphics API", n_summary_paras=3)),
    "Audio-API":         ("Audio-API.md",
                          lambda: gen_module_page("audio", "Audio API")),
    "Physics-API":       ("Physics-API.md",
                          lambda: gen_module_page("physics", "Physics API", n_summary_paras=3)),
    "Input-API":         ("Input-API.md",
                          lambda: gen_module_page("input", "Input API")),
    "Math-API":          ("Math-API.md",
                          lambda: gen_module_page("math", "Math API")),
    "Timer-API":         ("Timer-API.md",
                          lambda: gen_module_page("timer", "Timer API", n_summary_paras=3)),
    "Window-API":        ("Window-API.md",
                          lambda: gen_module_page("window", "Window API")),
    "Filesystem-API":    ("Filesystem-API.md",
                          lambda: gen_module_page("filesystem", "Filesystem API")),
    "Entity-API":        ("Entity-API.md",
                          lambda: gen_module_page("entity", "Entity API")),
    "Scene-API":         ("Scene-API.md",
                          lambda: gen_module_page("scene", "Scene API")),
    "Tilemap-API":       ("Tilemap-API.md",
                          lambda: gen_module_page("tilemap", "Tilemap API")),
    "AI-API":            ("AI-API.md",
                          lambda: gen_module_page("ai", "AI API", n_summary_paras=3)),
    "Pathfinding-API":   ("Pathfinding-API.md",
                          lambda: gen_module_page("pathfinding", "Pathfinding API")),
    "Threading":         ("Threading.md",
                          lambda: gen_module_page("thread", "Threading", n_summary_paras=3)),
    "Animation-API":     ("Animation-API.md",
                          lambda: gen_module_page("animation", "Animation API", n_summary_paras=3)),
    "Camera-API":        ("Camera-API.md",
                          lambda: gen_module_page("camera", "Camera API")),
    "Particle-API":      ("Particle-API.md",
                          lambda: gen_module_page("particle", "Particle API")),
    "GUI-API":           ("GUI-API.md",
                          lambda: gen_module_page("gui", "GUI API", n_summary_paras=3)),
    "Terminal-API":      ("Terminal-API.md",
                          lambda: gen_module_page("terminal", "Terminal API")),
    "Event-API":         ("Event-API.md",
                          lambda: gen_module_page("event", "Event API")),
    "Automation-API":    ("Automation-API.md",
                          lambda: gen_module_page("automation", "Automation API")),
    "Network-API":       ("Network-API.md",
                          lambda: gen_module_page("network", "Network API")),
    "Savegame-API":      ("Savegame-API.md",
                          lambda: gen_module_page("savegame", "Savegame API")),
    "Modding-API":       ("Modding-API.md",
                          lambda: gen_module_page("modding", "Modding API")),
    "Procgen-API":       ("Procgen-API.md",
                          lambda: gen_module_page("procgen", "Procedural Generation API")),
    # ── Sidebar + Footer ──────────────────────────────────────────────
    "_Sidebar":          ("_Sidebar.md",           gen_sidebar),
    "_Footer":           ("_Footer.md",            gen_footer),
}


# ═══════════════════════════════════════════════════════════════════════════════
# CLI entry point
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate all Luna2D wiki pages from source.",
    )
    parser.add_argument(
        "--page", metavar="SLUG",
        help="Regenerate a single page by slug (see --list for slugs)",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all available page slugs and exit",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print generated content without writing files",
    )
    args = parser.parse_args()

    if args.list:
        for slug, (filename, _) in PAGES.items():
            print(f"  {slug:25s}  →  wiki/{filename}")
        return 0

    WIKI.mkdir(parents=True, exist_ok=True)

    if args.page:
        if args.page not in PAGES:
            print(f"ERROR: unknown page slug '{args.page}'. Run --list to see options.",
                  file=sys.stderr)
            return 1
        targets = {args.page: PAGES[args.page]}
    else:
        targets = PAGES

    errors = 0
    for slug, (filename, gen_fn) in targets.items():
        try:
            content = gen_fn()
            write_page(filename, content, dry_run=args.dry_run)
        except Exception as exc:  # noqa: BLE001
            print(f"  ERROR  {filename}: {exc}", file=sys.stderr)
            errors += 1

    if not args.dry_run:
        total = len(targets)
        print(f"\n{'✓' if errors == 0 else '!'} {total - errors}/{total} pages written to wiki/")
    return 0 if errors == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
