#!/usr/bin/env python3
"""
gen_lua_api_html_wrapper.py — Generate HTML index wrapper for Lua API docs-general in ../lurek_2D_pages/lua-docs/.

The Markdown modules generated by gen_module_pages.py (in ../lurek_2D_pages/lua-docs/modules/*.md)
and the gen_docs_lua_html.py redirects need an index and top-level structure.

This wrapper generates:
  - ../lurek_2D_pages/lua-docs/index.html (landing page)
  - ../lurek_2D_pages/lua-docs/callbacks.html (redirect)
  - ../lurek_2D_pages/lua-docs/types.html (redirect)

Usage:
    python tools/docs/gen_lua_api_html_wrapper.py
"""

import json
import sys
from pathlib import Path
from html import escape
from datetime import datetime

WORKSPACE_ROOT = Path(__file__).resolve().parents[2]
PAGES_ROOT = WORKSPACE_ROOT.parent / f"{WORKSPACE_ROOT.name}_pages"
sys.path.insert(0, str(WORKSPACE_ROOT / "tools" / "docs"))
import module_registry

LUA_API_JSON = module_registry.lua_api_json_path()
OUTPUT_DIR = PAGES_ROOT / "lua-docs"

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Lurek2D Lua API</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: white;
            border-radius: 4px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }}
        header {{
            background: linear-gradient(135deg, #1b3a9e 0%, #0f1f5c 100%);
            color: white;
            padding: 30px 20px;
            margin: -20px -20px 30px -20px;
            border-radius: 4px 4px 0 0;
        }}
        header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        header p {{
            font-size: 1.1em;
            opacity: 0.9;
        }}
        h2 {{
            font-size: 1.5em;
            margin: 25px 0 15px 0;
            color: #0f1f5c;
        }}
        .module-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .module-card {{
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 20px;
            background: #f9f9f9;
            transition: all 0.3s ease;
        }}
        .module-card:hover {{
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            transform: translateY(-2px);
        }}
        .module-card h3 {{
            margin: 0 0 10px 0;
            font-size: 1.2em;
            color: #1b3a9e;
        }}
        .module-card p {{
            margin: 0;
            color: #666;
            font-size: 0.95em;
        }}
        .module-card a {{
            color: #1b3a9e;
            text-decoration: none;
        }}
        .module-card a:hover {{
            text-decoration: underline;
        }}
        .meta {{
            font-size: 0.85em;
            color: #999;
            margin-top: 10px;
        }}
        footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
            text-align: center;
        }}
        .nav-links {{
            display: flex;
            gap: 20px;
            margin: 30px 0;
        }}
        .nav-links a {{
            color: #1b3a9e;
            text-decoration: none;
            padding: 10px 20px;
            border: 1px solid #ddd;
            border-radius: 4px;
            transition: all 0.2s;
        }}
        .nav-links a:hover {{
            background: #f0f0f0;
        }}
    </style>
</head>
<body>
<div class="container">
    <header>
        <h1>Lurek2D Lua API</h1>
        <p>Complete reference for lurek.* modules</p>
    </header>

    <div class="nav-links">
        <a href="../">← Back to Documentation</a>
        <a href="callbacks.html">Callbacks</a>
        <a href="types.html">Type Reference</a>
    </div>

    {content}

    <footer>
        <p>Generated on {timestamp} | <a href="https://github.com/Lurek2D/lurek_2d">GitHub Repository</a></p>
    </footer>
</div>
</body>
</html>
"""

def load_api_data():
    """Load API data from JSON."""
    if not LUA_API_JSON.exists():
        return {}
    try:
        return json.loads(LUA_API_JSON.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"WARNING: Could not load API data: {e}")
        return {}

def generate_index(api_data: dict) -> str:
    """Generate index.html."""
    modules_data = api_data.get("lua_api", {}).get("modules", {}) or {}
    
    cards = []
    for module_name in sorted(modules_data.keys()):
        mod_data = modules_data[module_name]
        fn_count = len(mod_data.get("functions", []) or [])
        cls_count = len(mod_data.get("classes", {}) or {})
        
        cards.append(f'''
        <div class="module-card">
            <h3><a href="modules/{module_name}.html">{module_name.title()}</a></h3>
            <p>{mod_data.get("description", "").split(chr(10))[0] if mod_data.get("description") else "Lua module"}</p>
            <div class="meta">{fn_count} functions • {cls_count} types</div>
        </div>
        ''')
    
    content = f'''
    <h2>Modules</h2>
    <p>{len(modules_data)} API modules</p>
    <div class="module-grid">
        {''.join(cards)}
    </div>
    '''
    
    return HTML_TEMPLATE.format(
        title="Lua API Documentation",
        content=content,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )

def generate_redirect(target: str, title: str) -> str:
    """Generate HTML redirect page."""
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta http-equiv="refresh" content="0; url={target}">
  <style>
  body {{ font-family: Inter, Segoe UI, sans-serif; margin: 2rem; }}
  a {{ color: #1b6ca8; }}
  </style>
</head>
<body>
  <p>Redirecting to <a href="{target}">{target}</a>…</p>
</body>
</html>
'''

def main():
    api_data = load_api_data()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Generate index
    print(f"Generating {OUTPUT_DIR}/index.html...")
    (OUTPUT_DIR / "index.html").write_text(generate_index(api_data), encoding="utf-8")
    
    # Generate redirect pages
    print(f"Generating redirect pages...")
    (OUTPUT_DIR / "callbacks.html").write_text(generate_redirect("../callbacks.html", "Callbacks"), encoding="utf-8")
    (OUTPUT_DIR / "types.html").write_text(generate_redirect("../types.html", "Types"), encoding="utf-8")
    (OUTPUT_DIR / "search.html").write_text(generate_redirect("../search.html", "Search"), encoding="utf-8")
    
    print(f"[OK] Generated Lua API wrapper in {OUTPUT_DIR}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
