#!/usr/bin/env python3
"""sync_agent_rules.py — Synchronize workspace rules files with Lurek2D system prompt.

Reads the central system prompt from `.github/copilot-instructions.md` and generates/synchronizes:
  - `.antigravityrules`

This ensures Antigravity has direct access to Lurek2D's system rules and understands how to navigate the CAG layer.

Usage:
  python tools/github/sync_agent_rules.py
  python tools/github/sync_agent_rules.py --check
"""

import argparse
import sys
from pathlib import Path

# Paths relative to workspace root
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent.parent
COPILOT_INSTRUCTIONS_PATH = WORKSPACE_ROOT / ".github" / "copilot-instructions.md"

RULE_FILENAMES = [
    ".antigravityrules",
    ".cursorrules",
    ".clinerules",
    ".windsurfrules",
]

PREAMBLE_TEMPLATE = """# Lurek2D System Rules (Auto-generated)

> [!IMPORTANT]
> DO NOT edit this file directly. This file is auto-generated and kept in sync with
> `.github/copilot-instructions.md` by running `python tools/github/sync_agent_rules.py`.
> To update these rules, edit `.github/copilot-instructions.md` and run the sync script.

## Context Augmented Guidance (CAG) System
This repository is configured with a rich, model-agnostic CAG layer under `.github/`.
As an AI agent, you must dynamically discover and load relevant context depending on the task:

1. **System Prompt** (`.github/copilot-instructions.md`): Core constraints, identity, sync contracts, and discovery flows. ALWAYS in context.
2. **Agents** (`.github/agents/<name>.agent.md`): Specialist roles (mission, scope, workflows). Single-agent mode completes requests directly.
3. **Skills** (`.github/skills/<name>/SKILL.md`): Deep domain knowledge (when to load, domain facts). Loaded dynamically based on task descriptions.
4. **Prompts** (`.github/prompts/<verb>-<noun>.prompt.md`): Step-by-step checklists and playbook recipes.

When a user gives you a request:
- Map the request to a primary domain.
- Discover and load relevant skills (`SKILL.md`) matching the task.
- Check `.github/copilot-instructions.md` for binding constraints (T-xx, A-xx, B-xx, C-xx, TST-xx) and respect them.
- Follow the workflow rules, quality gates (`cargo test`, `cag_validate.py`), and commit format `type(scope): description`.

---

"""


def parse_args():
    from argparse import RawDescriptionHelpFormatter
    epilog = """
Examples:
  # Default execution
  python tools/github/sync_agent_rules.py

  # Show all arguments
  python tools/github/sync_agent_rules.py --help
"""
    parser = argparse.ArgumentParser(
        description="Synchronize workspace rules files with .github/copilot-instructions.md",
        epilog=epilog,
        formatter_class=RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if files are synchronized; exits 1 if mismatch found.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if not COPILOT_INSTRUCTIONS_PATH.exists():
        print(
            f"ERROR: Base system prompt not found at {COPILOT_INSTRUCTIONS_PATH}",
            file=sys.stderr,
        )
        return 2

    # Read base system prompt
    try:
        base_instructions = COPILOT_INSTRUCTIONS_PATH.read_text(encoding="utf-8")
    except Exception as e:
        print(
            f"ERROR: Failed to read {COPILOT_INSTRUCTIONS_PATH}: {e}",
            file=sys.stderr,
        )
        return 2

    # Build target contents
    target_content = PREAMBLE_TEMPLATE + base_instructions
    mismatches = []

    for name in RULE_FILENAMES:
        path = WORKSPACE_ROOT / name
        exists = path.exists()

        if exists:
            try:
                current_content = path.read_text(encoding="utf-8")
            except Exception as e:
                print(
                    f"ERROR: Failed to read {name}: {e}",
                    file=sys.stderr,
                )
                current_content = ""
        else:
            current_content = ""

        if current_content != target_content:
            mismatches.append((name, path, exists))

    if args.check:
        if mismatches:
            print("ERROR: Mismatched/unsynchronized agent rules files:", file=sys.stderr)
            for name, _, exists in mismatches:
                status = "out of sync" if exists else "missing"
                print(f"  - {name} ({status})", file=sys.stderr)
            print(
                "\nRun 'python tools/github/sync_agent_rules.py' to synchronize.",
                file=sys.stderr,
            )
            return 1
        print("All agent rules files are perfectly synchronized.")
        return 0

    # Write files if not checking
    for name, path, exists in mismatches:
        action = "Updating" if exists else "Creating"
        print(f"{action} {name}...")
        try:
            path.write_text(target_content, encoding="utf-8")
        except Exception as e:
            print(
                f"ERROR: Failed to write {name}: {e}",
                file=sys.stderr,
            )
            return 2

    if not mismatches:
        print("All agent rules files are already up-to-date and synchronized.")
    else:
        print("Successfully synchronized all agent rules files.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
