-- Evidence tests: awareness module.
-- @covers lurek.awareness.lineOfAction
-- @covers lurek.awareness.new
-- @covers lurek.awareness.newFov
-- @covers lurek.awareness.newTileAwareness
-- @covers lurek.filesystem.write
-- @covers lurek.image.newImageData
-- @covers lurek.image.savePNG
-- @covers lurek.tilefield.new


local OUT = evidence_output_dir("awareness")

local function save_png(img, path)
    lurek.image.savePNG(img, path)
    expect_evidence_created(path)
end

local function save_text(path, text)
    if write_file then
        write_file(path, text)
    else
        lurek.filesystem.write(path, text)
    end
    expect_evidence_created(path)
end

local function draw_outline(img, x, y, w, h, r, g, b, a)
    img:drawLine(x, y, x + w - 1, y, r, g, b, a or 255)
    img:drawLine(x + w - 1, y, x + w - 1, y + h - 1, r, g, b, a or 255)
    img:drawLine(x + w - 1, y + h - 1, x, y + h - 1, r, g, b, a or 255)
    img:drawLine(x, y + h - 1, x, y, r, g, b, a or 255)
end

local function paint_cell(img, x, y, cell, r, g, b)
    local ox = (x - 1) * cell
    local oy = (y - 1) * cell
    img:drawRect(ox, oy, cell, cell, r, g, b, 255)
    draw_outline(img, ox, oy, cell, cell, 22, 25, 34, 255)
end

local function state_color(state)
    if state == "visible" then
        return 92, 210, 120
    end
    if state == "discovered" then
        return 72, 92, 122
    end
    return 20, 24, 32
end

local function coord_key(x, y)
    return tostring(x) .. "," .. tostring(y)
end

-- @describe evidence: awareness
describe("evidence: awareness", function()
    before_each(function()
        ensure_evidence_dir("awareness")
    end)

    -- Does: Builds a region awareness grid with hidden, discovered, and visible states for two players.
    -- Shows: Region state transitions, region costs, flags, and player sharing as an inspectable 8x8 state map.
    -- Artifact: tests/artifacts/current/awareness/awareness_region_state_matrix.png
    -- Why: This gives the core LAwarenessGrid behavior a direct artifact instead of only tilefield-derived visibility.
    it("PNG: region state matrix", function()
        local awareness = lurek.awareness.new({ regions = 64, players = 2 })
        awareness:setGroup({ 0, 1 })
        for i = 0, 63 do
            awareness:setCost(i, 1.0 + (i % 5) * 0.5)
            if i % 7 == 0 then
                awareness:setFlag(i, 1, true)
            end
        end
        for i = 0, 63, 5 do
            awareness:reveal(0, i)
        end
        for i = 4, 63, 6 do
            awareness:reveal(0, i)
            awareness:hide(0, i)
        end
        for i = 2, 63, 9 do
            awareness:reveal(1, i)
        end

        local cell = 20
        local img = lurek.image.newImageData(8 * cell, 8 * cell)
        img:fill(8, 10, 16, 255)
        for region = 0, 63 do
            local x = (region % 8) + 1
            local y = math.floor(region / 8) + 1
            local r, g, b = state_color(awareness:getState(0, region))
            paint_cell(img, x, y, cell, r, g, b)
            if awareness:hasFlag(region, 1) then
                img:drawCircle((x - 1) * cell + math.floor(cell / 2), (y - 1) * cell + math.floor(cell / 2), 3, 255, 215, 80, 255)
            end
            if awareness:getState(1, region) == "visible" then
                img:drawLine((x - 1) * cell + 3, (y - 1) * cell + cell - 4, (x - 1) * cell + cell - 4, (y - 1) * cell + 3, 90, 170, 255, 255)
            end
        end
        draw_outline(img, 0, 0, 8 * cell, 8 * cell, 235, 238, 246, 255)
        save_png(img, OUT .. "awareness_region_state_matrix.png")
    end)

    -- Does: Computes field-of-view around blockers and exports a visual mask.
    -- Shows: Visible, explored, hidden, and blocked cells generated by LFov methods.
    -- Artifact: tests/artifacts/current/awareness/awareness_fov_blockers.png
    -- Why: This directly proves the standalone FOV owner rather than piggybacking on tilefield awareness.
    it("PNG: FOV blockers and explored mask", function()
        local width, height = 15, 12
        local blockers = {}
        for y = 1, height do
            for x = 1, width do
                if (x == 8 and y >= 2 and y <= 10 and y ~= 6) or (y == 8 and x >= 4 and x <= 13) then
                    blockers[coord_key(x, y)] = true
                end
            end
        end

        local fov = lurek.awareness.newFov({ range = 7, width = width, height = height })
        fov:setBlocker(function(x, y)
            return blockers[coord_key(x, y)] == true
        end)
        fov:compute(4, 6)
        fov:compute(12, 4)

        local cell = 18
        local img = lurek.image.newImageData(width * cell, height * cell)
        img:fill(8, 10, 16, 255)
        for y = 1, height do
            for x = 1, width do
                if blockers[coord_key(x, y)] then
                    paint_cell(img, x, y, cell, 82, 42, 48)
                elseif fov:isVisible(x, y) then
                    paint_cell(img, x, y, cell, 95, 215, 130)
                elseif fov:isExplored(x, y) then
                    paint_cell(img, x, y, cell, 70, 88, 118)
                else
                    paint_cell(img, x, y, cell, 18, 22, 30)
                end
            end
        end
        img:drawCircle(math.floor((4 - 0.5) * cell), math.floor((6 - 0.5) * cell), 4, 255, 218, 80, 255)
        img:drawCircle(math.floor((12 - 0.5) * cell), math.floor((4 - 0.5) * cell), 4, 92, 170, 255, 255)
        draw_outline(img, 0, 0, width * cell, height * cell, 235, 238, 246, 255)
        save_png(img, OUT .. "awareness_fov_blockers.png")
    end)

    -- Does: Computes tile-aware vision, action, cone awareness, and team sharing on a hex tilefield.
    -- Shows: Hex topology, blocker categories, blue/red player visibility, action reach, and shared cone cells.
    -- Artifact: tests/artifacts/current/awareness/awareness_hex_cone_share.png
    -- Why: This gives awareness its own combination artifact for hex maps instead of leaving the proof in tilefield.
    it("PNG: hex cone and team share", function()
        local width, height = 13, 10
        local field = lurek.tilefield.new({ width = width, height = height, topology = "hex" })
        field:defineCategory("sight", { kind = "awareness" })
        for y = 2, 9 do
            if y ~= 5 then
                field:setCategoryBlock(7, y, 1, "sight", true)
                field:setBlock(7, y, 1, "action", true)
            end
        end

        local vis = lurek.awareness.newTileAwareness(field, { players = { "blue", "red" }, rememberExplored = true })
        vis:defineCategory("sight", {
            active = true,
            range = 5,
            mode = "cone",
            arc = 100,
            facing = { x = 1, y = 0 },
            blockerCategory = "sight",
        })
        vis:computeVisible("blue", { origin = { x = 3, y = 5, z = 1 }, category = "sight" })
        vis:computeAction("blue", { origin = { x = 3, y = 5, z = 1 }, range = 4, channel = "action" })
        vis:computeVisible("red", { origin = { x = 11, y = 6, z = 1 }, range = 3 })
        vis:share("blue", "red", "sight")

        local cell = 18
        local img = lurek.image.newImageData(width * cell + math.floor(cell / 2), height * cell)
        img:fill(8, 10, 16, 255)
        for y = 1, height do
            local offset = (y % 2 == 0) and math.floor(cell / 2) or 0
            for x = 1, width do
                local ox = offset + (x - 1) * cell
                local oy = (y - 1) * cell
                local r, g, b = 20, 24, 32
                if field:blocksCategory(x, y, 1, "sight") then
                    r, g, b = 82, 42, 48
                elseif vis:isAware("blue", "sight", x, y, 1) and vis:isVisible("red", x, y, 1) then
                    r, g, b = 138, 104, 214
                elseif vis:isAware("blue", "sight", x, y, 1) then
                    r, g, b = 78, 158, 255
                elseif vis:isVisible("red", x, y, 1) then
                    r, g, b = 255, 108, 102
                elseif vis:isExplored("blue", x, y, 1) then
                    r, g, b = 62, 78, 104
                end
                img:drawRect(ox, oy, cell, cell, r, g, b, 255)
                if vis:canActOn("blue", x, y, 1) then
                    img:drawCircle(ox + math.floor(cell / 2), oy + math.floor(cell / 2), 3, 255, 218, 80, 255)
                end
                draw_outline(img, ox, oy, cell, cell, 22, 25, 34, 255)
            end
        end
        img:drawCircle(math.floor((3 - 0.5) * cell), math.floor((5 - 0.5) * cell), 5, 80, 165, 255, 255)
        img:drawCircle(math.floor((11 - 0.5) * cell) + math.floor(cell / 2), math.floor((6 - 0.5) * cell), 5, 255, 108, 102, 255)
        draw_outline(img, 0, 0, width * cell + math.floor(cell / 2), height * cell, 235, 238, 246, 255)
        save_png(img, OUT .. "awareness_hex_cone_share.png")

        local lines = {
            "blue_sight_cells=" .. tostring(#vis:visibleCells("blue", "sight", 1)),
            "blue_action_cells=" .. tostring(#vis:actionCells("blue", 1)),
            "red_shared_sight_cells=" .. tostring(#vis:visibleCells("red", "sight", 1)),
            "line_of_action_blocked=" .. tostring(not lurek.awareness.lineOfAction(field, { x = 3, y = 5, z = 1 }, { x = 11, y = 5, z = 1 })),
        }
        save_text(OUT .. "awareness_tilefield_action_trace.txt", table.concat(lines, "\n") .. "\n")
    end)
end)

test_summary()
