-- Evidence tests: advanced render module
-- Artifacts are generated by lurek.render and captured through render API output.

local OUT = "tests/output/render_advanced/"

local function capture_png(name)
    local path = OUT .. name
    lurek.render.captureScreenshot(function(img)
        lurek.image.savePNG(img, path)
    end)
    expect_evidence_created(path)
end

-- @describe Evidence: advanced lurek.render API
describe("Evidence: advanced lurek.render API", function()
    before_each(function()
        ensure_evidence_dir("render_advanced")
        lurek.render.clear(0.08, 0.08, 0.12)
    end)

    -- @evidence file
    it("R01 PNG: rectangles", function()
        lurek.render.setColor(0.9, 0.3, 0.3, 1.0)
        lurek.render.rectangle("fill", 24, 24, 120, 70)
        lurek.render.setColor(0.3, 0.8, 0.9, 1.0)
        lurek.render.rectangle("line", 170, 24, 120, 70)
        capture_png("r01_rectangles.png")
    end)

    -- @evidence file
    it("R02 PNG: circle and ellipse", function()
        lurek.render.setColor(0.9, 0.8, 0.3, 1.0)
        lurek.render.circle("fill", 90, 90, 50)
        lurek.render.setColor(0.3, 0.9, 0.5, 1.0)
        lurek.render.ellipse("line", 230, 90, 70, 35)
        capture_png("r02_circle_ellipse.png")
    end)

    -- @evidence file
    it("R03 PNG: triangle and polygon", function()
        lurek.render.setColor(0.9, 0.4, 0.4, 1.0)
        lurek.render.triangle("fill", 40, 150, 130, 50, 180, 150)
        lurek.render.setColor(0.4, 0.7, 0.95, 1.0)
        lurek.render.polygon("line", 220, 150, 260, 95, 315, 110, 300, 165, 240, 175)
        capture_png("r03_triangle_polygon.png")
    end)

    -- @evidence file
    it("R04 PNG: line polyline arc", function()
        lurek.render.setColor(0.9, 0.9, 0.9, 1.0)
        lurek.render.setLineWidth(2)
        lurek.render.line(20, 30, 300, 30)
        lurek.render.line(20, 60, 80, 85)
        lurek.render.line(80, 85, 140, 70)
        lurek.render.line(140, 70, 200, 110)
        lurek.render.line(200, 110, 280, 90)
        lurek.render.setColor(0.95, 0.7, 0.3, 1.0)
        lurek.render.arc("line", 170, 150, 55, 0.0, math.pi * 1.35)
        capture_png("r04_line_polyline_arc.png")
    end)

    -- @evidence file
    it("R05 PNG: transform stack", function()
        lurek.render.push()
        lurek.render.translate(110, 90)
        lurek.render.rotate(0.5)
        lurek.render.scale(1.2, 1.2)
        lurek.render.setColor(0.4, 0.85, 0.55, 1.0)
        lurek.render.rectangle("fill", -40, -25, 80, 50)
        lurek.render.pop()

        lurek.render.setColor(0.9, 0.4, 0.7, 1.0)
        lurek.render.rectangle("line", 220, 60, 80, 50)
        capture_png("r05_transform_stack.png")
    end)

    -- @evidence file
    it("R06 PNG: scissor region", function()
        lurek.render.setScissor(40, 30, 140, 100)
        lurek.render.setColor(0.95, 0.35, 0.35, 1.0)
        lurek.render.rectangle("fill", 0, 0, 320, 180)
        lurek.render.intersectScissor(80, 50, 80, 60)
        lurek.render.setColor(0.35, 0.8, 0.95, 1.0)
        lurek.render.rectangle("fill", 0, 0, 320, 180)
        lurek.render.setScissor()
        capture_png("r06_scissor.png")
    end)

    -- @evidence file
    it("R07 PNG: blend mode alpha", function()
        lurek.render.setBlendMode("alpha")
        lurek.render.setColor(1.0, 0.2, 0.2, 0.6)
        lurek.render.circle("fill", 120, 95, 55)
        lurek.render.setColor(0.2, 0.2, 1.0, 0.6)
        lurek.render.circle("fill", 180, 95, 55)
        capture_png("r07_blend_alpha.png")
    end)

    -- @evidence file
    it("R08 PNG: stencil mode setup", function()
        lurek.render.clearStencil()
        lurek.render.setStencilMode("replace", "always", 1)
        lurek.render.setStencilTest("greater", 0)
        lurek.render.setColor(0.95, 0.75, 0.35, 1.0)
        lurek.render.rectangle("fill", 60, 40, 200, 100)
        capture_png("r08_stencil_setup.png")
    end)

    -- @evidence file
    it("R09 PNG: depth and wireframe toggles", function()
        lurek.render.setDepthMode("less", true)
        lurek.render.setWireframe(true)
        lurek.render.setColor(0.4, 0.9, 0.5, 1.0)
        lurek.render.rectangle("line", 70, 45, 180, 90)
        lurek.render.setWireframe(false)
        lurek.render.setDepthMode("always", false)
        capture_png("r09_depth_wireframe.png")
    end)

    -- @evidence file
    it("R10 PNG: color mask", function()
        lurek.render.setColorMask(true, false, false, true)
        lurek.render.setColor(1.0, 0.2, 0.2, 1.0)
        lurek.render.rectangle("fill", 20, 20, 120, 80)
        lurek.render.setColorMask(false, true, false, true)
        lurek.render.setColor(0.2, 1.0, 0.2, 1.0)
        lurek.render.rectangle("fill", 100, 60, 120, 80)
        lurek.render.setColorMask(true, true, true, true)
        capture_png("r10_color_mask.png")
    end)
end)

test_summary()
