-- Evidence tests: additional minimap cases
-- Artifacts are generated by lurek.minimap drawToImage and state APIs.

local OUT = "tests/output/minimap/"

-- @describe Evidence: additional lurek.minimap API
describe("Evidence: additional lurek.minimap API", function()
    before_each(function()
        ensure_evidence_dir("minimap")
    end)

    local function save_mm(mm, pixel_size, name)
        local img = mm:drawToImage(pixel_size)
        local path = OUT .. name
        lurek.image.savePNG(img, path)
        expect_evidence_created(path)
    end

    -- @evidence file
    it("MM01 PNG: fog data table", function()
        local mm = lurek.minimap.newMinimap(12, 12, 120, 120)
        mm:setFogEnabled(true)
        mm:setFogColor(0.03, 0.03, 0.05, 1.0)

        local fog = {}
        for y = 1, 12 do
            for x = 1, 12 do
                local d = math.abs(x - 6) + math.abs(y - 6)
                fog[#fog + 1] = math.min(255, d * 20)
                mm:setTerrain(x, y, (x + y) % 3)
            end
        end
        mm:setFogData(fog)

        save_mm(mm, 8, "mm01_fog_data.png")
    end)

    -- @evidence file
    it("MM02 PNG: marker add/remove", function()
        local mm = lurek.minimap.newMinimap(16, 10, 160, 100)
        for y = 1, 10 do
            for x = 1, 16 do
                mm:setTerrain(x, y, ((x * 3 + y) % 4))
            end
        end

        local m1 = mm:addMarker(20, 30, "A", 0.2, 1.0, 0.2, 1.0)
        local m2 = mm:addMarker(100, 50, "B", 1.0, 0.2, 0.2, 1.0)
        expect_true(m1 > 0 and m2 > 0)
        mm:removeMarker(m1)

        save_mm(mm, 8, "mm02_marker_remove.png")
    end)

    -- @evidence file
    it("MM03 PNG: viewport toggle", function()
        local mm = lurek.minimap.newMinimap(20, 12, 200, 120)
        for y = 1, 12 do
            for x = 1, 20 do
                mm:setTerrain(x, y, ((x + y) % 5))
            end
        end

        mm:setViewportRect(40, 20, 80, 60)
        mm:setViewportColor(1.0, 0.9, 0.3, 1.0)
        mm:setViewportVisible(false)
        save_mm(mm, 8, "mm03_viewport_hidden.png")

        mm:setViewportVisible(true)
        save_mm(mm, 8, "mm03_viewport_visible.png")
    end)

    -- @evidence file
    it("MM04 PNG: path overlay", function()
        local mm = lurek.minimap.newMinimap(18, 18, 180, 180)
        for y = 1, 18 do
            for x = 1, 18 do
                mm:setTerrain(x, y, ((x + y) % 5))
            end
        end

        mm:showPath({
            { 12.0, 160.0 },
            { 36.0, 132.0 },
            { 66.0, 108.0 },
            { 96.0, 86.0 },
            { 132.0, 54.0 },
            { 162.0, 30.0 },
        }, { 120, 255, 120, 255 })

        save_mm(mm, 8, "mm04_path_overlay.png")
    end)

    -- @evidence file
    it("MM05 PNG: marker animation update", function()
        local mm = lurek.minimap.newMinimap(14, 14, 140, 140)
        for y = 1, 14 do
            for x = 1, 14 do
                mm:setTerrain(x, y, (x * y) % 4)
            end
        end

        local id = mm:addMarker(70, 70, "Pulse", 0.9, 0.9, 0.2, 1.0)
        mm:setMarkerAnimation(id, "pulse", 2.0)
        mm:update(0.5)

        save_mm(mm, 8, "mm05_marker_animation.png")
    end)
end)

test_summary()
