// Autogenerated to group integration tests
#[path = "rust/ext/graphics_ext_tests.rs"]
mod graphics_ext_tests;
#[path = "rust/ext/graphics_runtime_smoke_tests.rs"]
mod graphics_runtime_smoke_tests;
#[path = "rust/ext/math_ext_tests.rs"]
mod math_ext_tests;
#[path = "rust/ext/terminal_demo_smoke_tests.rs"]
mod terminal_demo_smoke_tests;
#[path = "rust/integration/messages_tests.rs"]
mod messages_tests;
