//! Defines UI accessibility snapshots and diagnostics that expose retained-tree state without granting mutation authority.
//! UiAccessibilityNode records printable metadata, while UiDiagnostic carries bounded warnings for caller inspection.
//! GuiContext creates these from live state; Lua bindings serialize them but never expose indices as handles.
//! Open this file for diagnostic vocabulary, accessibility snapshot fields, and invariant failures visible to UI users.

/// A flattened accessibility snapshot entry describing one live widget.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiAccessibilityNode {
    /// Widget index in `GuiContext::widgets`.
    pub widget_idx: usize,
    /// Canonical widget type name such as `"button"` or `"textinput"`.
    pub widget_type: String,
    /// Semantic role used for accessibility and diagnostics.
    pub role: String,
    /// Accessible name after applying text and label fallback rules.
    pub name: String,
    /// Extended accessible description text.
    pub description: String,
    /// Optional widget index this node labels.
    pub label_for: Option<usize>,
    /// Whether this widget participates in keyboard focus traversal.
    pub focusable: bool,
    /// Whether the widget is currently visible in effective tree state.
    pub visible: bool,
    /// Whether the widget is enabled for interaction.
    pub enabled: bool,
}

/// A lightweight UX or accessibility warning associated with the live UI tree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiDiagnostic {
    /// Optional widget index associated with this diagnostic.
    pub widget_idx: Option<usize>,
    /// Human-readable warning or error text.
    pub message: String,
}

/// Read-only bounded telemetry for the most recent UI work and process lifetime.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct UiRuntimeStats {
    /// Number of live retained widgets excluding the root.
    pub live_widgets: usize,
    /// Commands generated by the most recent lowering pass.
    pub last_frame_commands: usize,
    /// Total layout passes performed by this context.
    pub layout_passes: u64,
    /// High-water mark of queued UI events.
    pub event_queue_high_water: usize,
    /// Number of render command lists truncated at the configured limit.
    pub command_limit_rejections: u64,
    /// Number of render-command lowerings served from the retained cache.
    pub command_cache_hits: u64,
    /// Number of render-command lowerings that rebuilt a fresh command stream.
    pub command_cache_misses: u64,
}

impl UiDiagnostic {
    /// Creates a diagnostic message optionally tied to a widget index.
    pub(crate) fn new(widget_idx: Option<usize>, message: impl Into<String>) -> Self {
        Self {
            widget_idx,
            message: message.into(),
        }
    }
}
