-- Auto-generated tests for process_map.lua
-- Generated by Lurek2D Toolkit

local passed = 0
local failed = 0
local total = 0

local function test(name, fn)
  total = total + 1
  local ok, err = pcall(fn)
  if ok then
    passed = passed + 1
    print("[PASS] " .. name)
  else
    failed = failed + 1
    print("[FAIL] " .. name .. ": " .. tostring(err))
  end
end

-- Tests for lurek.image

test("lurek.image.newImageData works", function()
  -- Source line 81: local next = lurek.image.newImageData(w, h)
  -- TODO: Add proper test assertion
  local result = lurek.image.newImageData()
  assert(result ~= nil, "lurek.image.newImageData should return a value")
end)

test("lurek.image.loadImage works", function()
  -- Source line 115: local src = lurek.image.loadImage(MAP_IN)
  -- TODO: Add proper test assertion
  local result = lurek.image.loadImage()
  assert(result ~= nil, "lurek.image.loadImage should return a value")
end)

test("lurek.image.savePNG works", function()
  -- Source line 303: lurek.image.savePNG(out, MAP_OUT)
  -- TODO: Add proper test assertion
  local result = lurek.image.savePNG()
  assert(result ~= nil, "lurek.image.savePNG should return a value")
end)

-- Tests for lurek.event

test("lurek.event.quit works", function()
  -- Source line 306: lurek.event.quit()
  -- TODO: Add proper test assertion
  local result = lurek.event.quit()
  assert(result ~= nil, "lurek.event.quit should return a value")
end)

-- Tests for lurek.render

test("lurek.render.clear works", function()
  -- Source line 311: lurek.render.clear(0, 0, 0)
  -- TODO: Add proper test assertion
  local result = lurek.render.clear()
  assert(result ~= nil, "lurek.render.clear should return a value")
end)

test("lurek.render.print works", function()
  -- Source line 312: lurek.render.print("[process_map] Przetwarzanie... sprawdź konsolę.", 10, 10)
  -- TODO: Add proper test assertion
  local result = lurek.render.print()
  assert(result ~= nil, "lurek.render.print should return a value")
end)

-- Summary
print(string.format("\n%d/%d tests passed (%d failed)", passed, total, failed))
if failed > 0 then
  error(string.format("%d tests failed", failed))
end
