[window]
title = "Lurek Workbench"
width = 1600
height = 900
fullscreen = false
resizable = true
maximized = true
vsync = true
scale_mode = "none"

[render]
default_font_size = 10

[engine]
target_fps = 60
