describe("dyna_blaster demo", function()
    local read_file_fn = rawget(_G, "read_file")

    it("requires scene, ecs, render and ui APIs", function()
        assert(type(lurek.scene.new) == "function", "lurek.scene.new must exist")
        assert(type(lurek.ecs.newUniverse) == "function", "lurek.ecs.newUniverse must exist")
        assert(type(lurek.render.rectangle) == "function", "lurek.render.rectangle must exist")
        assert(type(lurek.ui.loadLayoutFile) == "function", "lurek.ui.loadLayoutFile must exist")
    end)

    it("contains required game callbacks", function()
        assert(type(read_file_fn) == "function", "read_file helper must be available in Lua harness")
        local source = read_file_fn("content/games/arcade/dyna_blaster/main.lua")
        assert(source ~= nil, "main.lua must be readable")
        assert(source:find("function lurek.init", 1, true) ~= nil, "lurek.init callback missing")
        assert(source:find("function lurek.process", 1, true) ~= nil, "lurek.process callback missing")
        assert(source:find("function lurek.draw", 1, true) ~= nil, "lurek.draw callback missing")
    end)

    it("ships a UI layout file", function()
        assert(type(read_file_fn) == "function", "read_file helper must be available in Lua harness")
        local layout = read_file_fn("content/games/arcade/dyna_blaster/ui.toml")
        assert(layout ~= nil, "ui.toml must exist")
        assert(layout:find("score_label", 1, true) ~= nil, "score_label must exist in ui.toml")
    end)
end)
