-- content/examples/collision.lua
-- Lurek2D lurek.collision API Reference
-- Run with: cargo run -- content/examples/collision

-- =============================================================================
-- STUBS: 4 uncovered lurek.collision API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.collision.testAABB --------------------------------------
--@api-stub: lurek.collision.testAABB
-- Demonstrates the proper usage of lurek.collision.testAABB.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_collision_testAABB()
    lurek.collision.testAABB(ax, ay, aw, ah, bx, by, bw, bh)  -- -> boolean
end
local _ok, _err = pcall(demo_lurek_collision_testAABB)


--@api-stub: lurek.collision.testCircles
-- Demonstrates the proper usage of lurek.collision.testCircles.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_collision_testCircles()
    lurek.collision.testCircles(ax, ay, ar, bx, by, br)  -- -> boolean
end
local _ok, _err = pcall(demo_lurek_collision_testCircles)


--@api-stub: lurek.collision.testPoint
-- Demonstrates the proper usage of lurek.collision.testPoint.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_collision_testPoint()
    lurek.collision.testPoint(px, py, ax, ay, aw, ah)  -- -> boolean
end
local _ok, _err = pcall(demo_lurek_collision_testPoint)


--@api-stub: lurek.collision.testCircleAABB
-- Demonstrates the proper usage of lurek.collision.testCircleAABB.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_collision_testCircleAABB()
    lurek.collision.testCircleAABB(cx, cy, cr, ax, ay, aw, ah)  -- -> boolean
end
local _ok, _err = pcall(demo_lurek_collision_testCircleAABB)
