-- content/examples/fileapp.lua
-- Lurek2D lurek.filesystem API Reference
-- Run with: cargo run -- content/examples/filesystem

-- =============================================================================
-- STUBS: 49 uncovered lurek.filesystem API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.filesystem.mountZip -------------------------------------
--@api-stub: lurek.filesystem.mountZip
-- Demonstrates the proper usage of lurek.filesystem.mountZip.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_mountZip()
    local zm = lurek.filesystem.mountZip("assets/pack.zip", "pack/")
    print("zip prefix:", zm:prefix())
end
local _ok, _err = pcall(demo_lurek_filesystem_mountZip)

-- ---- Stub: lurek.filesystem.watchPath ------------------------------------
--@api-stub: lurek.filesystem.watchPath
-- Demonstrates the proper usage of lurek.filesystem.watchPath.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_watchPath()
    lurek.filesystem.watchPath("assets/hero.png")
    print("watching assets/hero.png")
end
local _ok, _err = pcall(demo_lurek_filesystem_watchPath)

-- ---- Stub: lurek.filesystem.unwatchPath ----------------------------------
--@api-stub: lurek.filesystem.unwatchPath
-- Demonstrates the proper usage of lurek.filesystem.unwatchPath.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_unwatchPath()
    lurek.filesystem.unwatchPath("assets/hero.png")
    print("unwatched assets/hero.png")
end
local _ok, _err = pcall(demo_lurek_filesystem_unwatchPath)

-- ---- Stub: lurek.filesystem.pollWatchers ---------------------------------
--@api-stub: lurek.filesystem.pollWatchers
-- Call once per second in the background to collect changed paths then
-- reload only the assets that actually changed on disk.
local changed = lurek.filesystem.pollWatchers()
if #changed > 0 then
    for _, p in ipairs(changed) do
        print("changed:", p)
    end
end

-- ---- Stub: lurek.filesystem.read -----------------------------------------
--@api-stub: lurek.filesystem.read
-- Demonstrates the proper usage of lurek.filesystem.read.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_read()
    local src = lurek.filesystem.read("data/level_01.txt")
    print("level data length:", #src)
end
local _ok, _err = pcall(demo_lurek_filesystem_read)

-- ---- Stub: lurek.filesystem.write ----------------------------------------
--@api-stub: lurek.filesystem.write
-- Demonstrates the proper usage of lurek.filesystem.write.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_write()
    lurek.filesystem.write("save/settings.txt", "volume=80\nfullscreen=true\n")
    print("settings saved")
end
local _ok, _err = pcall(demo_lurek_filesystem_write)

-- ---- Stub: lurek.filesystem.exists ---------------------------------------
--@api-stub: lurek.filesystem.exists
-- Guard asset loading so a missing optional file does not crash the
-- game -- fall back to defaults when the file is absent.
if lurek.filesystem.exists("save/progress.dat") then
    print("save file found")
else
    print("no save file -- starting fresh")
end

-- ---- Stub: lurek.filesystem.append ---------------------------------------
--@api-stub: lurek.filesystem.append
-- Demonstrates the proper usage of lurek.filesystem.append.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_append()
    lurek.filesystem.append("logs/session.log", "[INFO] player spawned\n")
    print("log entry appended")
end
local _ok, _err = pcall(demo_lurek_filesystem_append)

-- ---- Stub: lurek.filesystem.openFile -------------------------------------
--@api-stub: lurek.filesystem.openFile
-- Open a file handle for line-by-line reading of a large CSV tile map
-- that would be expensive to load entirely into memory at once.
local fh = lurek.filesystem.openFile("data/tilemap.csv", "r")
if fh then
    print("file open, size:", fh:getSize())
    fh:close()
end

-- ---- Stub: lurek.filesystem.getDirectoryItems ----------------------------
--@api-stub: lurek.filesystem.getDirectoryItems
-- List all save slot files to populate a load-game screen with the
-- player's existing save files.
local items = lurek.filesystem.getDirectoryItems("save/")
print("save directory items:", #items)
for _, name in ipairs(items) do print(" -", name) end

-- ---- Stub: lurek.filesystem.isFile ---------------------------------------
--@api-stub: lurek.filesystem.isFile
-- Demonstrates the proper usage of lurek.filesystem.isFile.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_isFile()
    print("is file:", lurek.filesystem.isFile("data/level_01.txt"))
end
local _ok, _err = pcall(demo_lurek_filesystem_isFile)

-- ---- Stub: lurek.filesystem.isDirectory ----------------------------------
--@api-stub: lurek.filesystem.isDirectory
-- Demonstrates the proper usage of lurek.filesystem.isDirectory.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_isDirectory()
    print("is directory:", lurek.filesystem.isDirectory("save/"))
end
local _ok, _err = pcall(demo_lurek_filesystem_isDirectory)

-- ---- Stub: lurek.filesystem.createDirectory ------------------------------
--@api-stub: lurek.filesystem.createDirectory
-- Demonstrates the proper usage of lurek.filesystem.createDirectory.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_createDirectory()
    lurek.filesystem.createDirectory("save/slots/slot_01/")
    print("save directory created")
end
local _ok, _err = pcall(demo_lurek_filesystem_createDirectory)

-- ---- Stub: lurek.filesystem.remove ---------------------------------------
--@api-stub: lurek.filesystem.remove
-- Demonstrates the proper usage of lurek.filesystem.remove.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_remove()
    lurek.filesystem.remove("save/slots/slot_01/progress.dat")
    print("old save removed")
end
local _ok, _err = pcall(demo_lurek_filesystem_remove)

-- ---- Stub: lurek.filesystem.getInfo -------------------------------------
--@api-stub: lurek.filesystem.getInfo
-- Read modification time and size before deciding whether to reload a
-- cached asset or continue using the in-memory version.
local info = lurek.filesystem.getInfo("assets/hero.png")
if info then
    print("size:", info.size, "modified:", info.modtime)
end

-- ---- Stub: lurek.filesystem.getSource ------------------------------------
--@api-stub: lurek.filesystem.getSource
-- Demonstrates the proper usage of lurek.filesystem.getSource.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_getSource()
    print("game source:", lurek.filesystem.getSource())
end
local _ok, _err = pcall(demo_lurek_filesystem_getSource)

-- ---- Stub: lurek.filesystem.getSaveDirectory -----------------------------
--@api-stub: lurek.filesystem.getSaveDirectory
-- Demonstrates the proper usage of lurek.filesystem.getSaveDirectory.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_getSaveDirectory()
    print("save dir:", lurek.filesystem.getSaveDirectory())
end
local _ok, _err = pcall(demo_lurek_filesystem_getSaveDirectory)

-- ---- Stub: lurek.filesystem.getWorkingDirectory --------------------------
--@api-stub: lurek.filesystem.getWorkingDirectory
-- Demonstrates the proper usage of lurek.filesystem.getWorkingDirectory.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_getWorkingDirectory()
    print("working dir:", lurek.filesystem.getWorkingDirectory())
end
local _ok, _err = pcall(demo_lurek_filesystem_getWorkingDirectory)

-- ---- Stub: lurek.filesystem.getUserDirectory -----------------------------
--@api-stub: lurek.filesystem.getUserDirectory
-- Demonstrates the proper usage of lurek.filesystem.getUserDirectory.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_getUserDirectory()
    print("user dir:", lurek.filesystem.getUserDirectory())
end
local _ok, _err = pcall(demo_lurek_filesystem_getUserDirectory)

-- ---- Stub: lurek.filesystem.getIdentity ----------------------------------
--@api-stub: lurek.filesystem.getIdentity
-- Demonstrates the proper usage of lurek.filesystem.getIdentity.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_getIdentity()
    print("game identity:", lurek.filesystem.getIdentity())
end
local _ok, _err = pcall(demo_lurek_filesystem_getIdentity)

-- ---- Stub: lurek.filesystem.setIdentity ----------------------------------
--@api-stub: lurek.filesystem.setIdentity
-- Demonstrates the proper usage of lurek.filesystem.setIdentity.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_setIdentity()
    lurek.filesystem.setIdentity("dungeon_escape")
    print("identity set:", lurek.filesystem.getIdentity())
end
local _ok, _err = pcall(demo_lurek_filesystem_setIdentity)

-- ---- Stub: lurek.filesystem.lines ----------------------------------------
--@api-stub: lurek.filesystem.lines
-- Iterate a dialogue script file line by line to parse NPC speech
-- entries without allocating the entire file as a single string.
local line_count = 0
for line in lurek.filesystem.lines("data/dialogue.txt") do
    line_count = line_count + 1
end
print("lines in dialogue:", line_count)

-- ---- Stub: lurek.filesystem.readAsync ------------------------------------
--@api-stub: lurek.filesystem.readAsync
-- Demonstrates the proper usage of lurek.filesystem.readAsync.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_readAsync()
    local handle_id = lurek.filesystem.readAsync("audio/boss_theme.ogg")
    print("async load started, handle:", handle_id)
end
local _ok, _err = pcall(demo_lurek_filesystem_readAsync)

-- ---- Stub: lurek.filesystem.pollAsync ------------------------------------
--@api-stub: lurek.filesystem.pollAsync
-- Demonstrates the proper usage of lurek.filesystem.pollAsync.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_pollAsync()
    local status, data = lurek.filesystem.pollAsync(handle_id)
    print("async status:", status)
end
local _ok, _err = pcall(demo_lurek_filesystem_pollAsync)

-- ---- Stub: lurek.filesystem.mount ----------------------------------------
--@api-stub: lurek.filesystem.mount
-- Demonstrates the proper usage of lurek.filesystem.mount.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_mount()
    local ok = lurek.filesystem.mount("mods/retro_pack/assets/", "assets/")
    print("mod mounted:", ok)
end
local _ok, _err = pcall(demo_lurek_filesystem_mount)

-- ---- Stub: lurek.filesystem.unmount --------------------------------------
--@api-stub: lurek.filesystem.unmount
-- Demonstrates the proper usage of lurek.filesystem.unmount.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_unmount()
    local removed = lurek.filesystem.unmount("assets/")
    print("mod unmounted:", removed)
end
local _ok, _err = pcall(demo_lurek_filesystem_unmount)

-- ---- Stub: lurek.filesystem.load -----------------------------------------
--@api-stub: lurek.filesystem.load
-- Demonstrates the proper usage of lurek.filesystem.load.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_load()
    local init_fn = lurek.filesystem.load("scripts/level_init.lua")
    if init_fn then init_fn() end
end
local _ok, _err = pcall(demo_lurek_filesystem_load)

-- ---- Stub: lurek.filesystem.newFileData ----------------------------------
--@api-stub: lurek.filesystem.newFileData
-- Demonstrates the proper usage of lurek.filesystem.newFileData.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_newFileData()
    local fd = lurek.filesystem.newFileData("assets/map.dat")
    print("file data size:", fd:getSize(), "bytes")
end
local _ok, _err = pcall(demo_lurek_filesystem_newFileData)

-- ---- Stub: lurek.filesystem.copy -----------------------------------------
--@api-stub: lurek.filesystem.copy
-- Demonstrates the proper usage of lurek.filesystem.copy.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_copy()
    lurek.filesystem.copy("save/autosave.dat", "save/autosave.bak")
    print("autosave backed up")
end
local _ok, _err = pcall(demo_lurek_filesystem_copy)

-- ---- Stub: lurek.filesystem.move -----------------------------------------
--@api-stub: lurek.filesystem.move
-- Demonstrates the proper usage of lurek.filesystem.move.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_move()
    lurek.filesystem.move("save/download.tmp", "save/patch.dat")
    print("file renamed to final name")
end
local _ok, _err = pcall(demo_lurek_filesystem_move)

-- ---- Stub: lurek.filesystem.removeDir ------------------------------------
--@api-stub: lurek.filesystem.removeDir
-- Demonstrates the proper usage of lurek.filesystem.removeDir.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_removeDir()
    lurek.filesystem.removeDir("save/slots/slot_01/")
    print("slot 1 deleted")
end
local _ok, _err = pcall(demo_lurek_filesystem_removeDir)

-- ---- Stub: lurek.filesystem.glob -----------------------------------------
--@api-stub: lurek.filesystem.glob
-- Find all PNG textures in the assets folder to build a dynamic atlas
-- at startup rather than hard-coding every texture name.
local textures = lurek.filesystem.glob("assets/sprites/*.png")
print("found", #textures, "sprites:")
for _, t in ipairs(textures) do print(" -", t) end

-- -----------------------------------------------------------------------------
-- FileData methods
-- -----------------------------------------------------------------------------

-- ---- Stub: FileData:getSize ----------------------------------------------
--@api-stub: FileData:getSize
-- Demonstrates the proper usage of FileData:getSize.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_FileData_getSize()
    print("file data bytes:", fd:getSize())
end
local _ok, _err = pcall(demo_FileData_getSize)

-- ---- Stub: FileData:getString --------------------------------------------
--@api-stub: FileData:getString
-- Demonstrates the proper usage of FileData:getString.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_FileData_getString()
    local raw = fd:getString()
    print("first 40 chars:", string.sub(raw, 1, 40))
end
local _ok, _err = pcall(demo_FileData_getString)

-- ---- Stub: FileData:getFilename ------------------------------------------
--@api-stub: FileData:getFilename
-- Demonstrates the proper usage of FileData:getFilename.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_FileData_getFilename()
    print("loaded from:", fd:getFilename())  -- "assets/map.dat"
end
local _ok, _err = pcall(demo_FileData_getFilename)

-- ---- Stub: FileHandle:read -----------------------------------------------
--@api-stub: FileHandle:read
-- Read a fixed-size binary record from a save file -- pass the byte
-- count to read exactly one record without over-reading.
local fh_r = lurek.filesystem.openFile("save/progress.dat", "r")
if fh_r then
    local record = fh_r:read(64)
    print("record bytes read:", #record)
    fh_r:close()
end

-- ---- Stub: FileHandle:readLine -------------------------------------------
--@api-stub: FileHandle:readLine
-- Parse a CSV row by reading one line at a time so the memory cost
-- stays constant for very large map files.
local fh_l = lurek.filesystem.openFile("data/tilemap.csv", "r")
if fh_l then
    local row = fh_l:readLine()
    print("first row:", row)
    fh_l:close()
end

-- ---- Stub: FileHandle:write ----------------------------------------------
--@api-stub: FileHandle:write
-- Serialise a settings table to the save directory by writing each
-- key-value pair as a line, then flushing to disk.
local fh_w = lurek.filesystem.openFile("save/settings.txt", "w")
if fh_w then
    local bytes = fh_w:write("volume=80\n")
    print("bytes written:", bytes)
    fh_w:flush()
    fh_w:close()
end

-- ---- Stub: FileHandle:seek -----------------------------------------------
--@api-stub: FileHandle:seek
-- Jump to a specific byte offset to read the header of a binary file
-- format without loading the entire file into memory.
local fh_s = lurek.filesystem.openFile("save/progress.dat", "r")
if fh_s then
    fh_s:seek(0)  -- rewind to start
    print("seeked to:", fh_s:tell())
    fh_s:close()
end

-- ---- Stub: FileHandle:tell -----------------------------------------------
--@api-stub: FileHandle:tell
-- Read the cursor position after seeking to verify the correct offset
-- before issuing a fixed-size read for a binary record.
local fh_t = lurek.filesystem.openFile("save/progress.dat", "r")
if fh_t then
    print("initial cursor:", fh_t:tell())  -- 0
    fh_t:close()
end

-- ---- Stub: FileHandle:getSize --------------------------------------------
--@api-stub: FileHandle:getSize
-- Check the file size before allocating a read buffer so oversized
-- files do not consume unexpected memory.
local fh_sz = lurek.filesystem.openFile("save/progress.dat", "r")
if fh_sz then
    print("file size:", fh_sz:getSize(), "bytes")
    fh_sz:close()
end

-- ---- Stub: FileHandle:getMode --------------------------------------------
--@api-stub: FileHandle:getMode
-- Verify the access mode before calling write to surface an early
-- programmer error when the wrong mode string was passed to openFile.
local fh_m = lurek.filesystem.openFile("save/progress.dat", "r")
if fh_m then
    print("mode:", fh_m:getMode())  -- "r"
    fh_m:close()
end

-- ---- Stub: FileHandle:flush ----------------------------------------------
--@api-stub: FileHandle:flush
-- Flush writes to disk after each autosave checkpoint so data is safe
-- even if the game crashes before the file is explicitly closed.
local fh_f = lurek.filesystem.openFile("save/autosave.dat", "w")
if fh_f then
    fh_f:write("checkpoint_1\n")
    fh_f:flush()  -- ensure checkpoint is on disk
    fh_f:close()
end

-- ---- Stub: FileHandle:close ----------------------------------------------
--@api-stub: FileHandle:close
-- Always close file handles after reading or writing to release the
-- OS file descriptor and ensure all buffered writes are committed.
local fh_c = lurek.filesystem.openFile("data/level_01.txt", "r")
if fh_c then
    local content = fh_c:read(256)
    fh_c:close()  -- release handle immediately after reading
    print("read", #content, "bytes")
end

-- ---- Stub: FileHandle:isEOF ----------------------------------------------
--@api-stub: FileHandle:isEOF
-- Loop reading lines from a text file until isEOF returns true so
-- the loop exits cleanly without needing the line count in advance.
local fh_eof = lurek.filesystem.openFile("data/dialogue.txt", "r")
if fh_eof then
    while not fh_eof:isEOF() do
        local line = fh_eof:readLine()
        if line then print(line) end
    end
    fh_eof:close()
end

-- -----------------------------------------------------------------------------
-- ZipMount methods
-- -----------------------------------------------------------------------------

-- ---- Stub: ZipMount:readFile ---------------------------------------------
--@api-stub: ZipMount:readFile
-- Demonstrates the proper usage of ZipMount:readFile.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ZipMount_readFile()
    local bytes = zm:readFile("pack/sprites/hero.png")
    print("sprite bytes from zip:", #bytes)
end
local _ok, _err = pcall(demo_ZipMount_readFile)

-- ---- Stub: ZipMount:contains ---------------------------------------------
--@api-stub: ZipMount:contains
-- Check whether an optional DLC asset exists inside the pack before
-- trying to load it so a missing asset gives a clean fallback.
if zm:contains("pack/audio/boss.ogg") then
    print("boss music found in DLC pack")
else
    print("boss music not included -- using default")
end

-- ---- Stub: ZipMount:listFiles --------------------------------------------
--@api-stub: ZipMount:listFiles
-- Enumerate all assets in the ZIP to build an index table at load time
-- so individual asset lookups do not need to iterate the archive.
local files = zm:listFiles()
print("files in zip:", #files)
for _, f in ipairs(files) do print(" -", f) end

-- ---- Stub: ZipMount:prefix -----------------------------------------------
--@api-stub: ZipMount:prefix
-- Demonstrates the proper usage of ZipMount:prefix.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ZipMount_prefix()
    print("mounted at prefix:", zm:prefix())  -- "pack/"
end
local _ok, _err = pcall(demo_ZipMount_prefix)

-- =============================================================================
-- New in 0.15.0: lurek.filesystem.listRecursive
-- =============================================================================

-- listRecursive returns all files under a directory tree as a flat list.
-- It raises an error if the path contains '..' (sandbox protection).
local ok, result = pcall(lurek.filesystem.listRecursive, "save/")
if ok then
  print(string.format("listRecursive found %d entries in save/", #result))
  for _, path in ipairs(result) do
    print("  " .. path)
  end
else
  print("save/ not found or empty (expected in a fresh game): " .. tostring(result))
end

-- Traversal attempts are rejected with an error:
local ok2, err2 = pcall(lurek.filesystem.listRecursive, "save/../..")
print("traversal blocked: " .. tostring(not ok2) .. " err: " .. tostring(err2))

-- =============================================================================
-- New in 0.15.0: lurek.filesystem.stat
-- =============================================================================

-- Write a file so stat has something to inspect.
lurek.filesystem.write("save/demo_stat.txt", "hello world")
local info = lurek.filesystem.stat("save/demo_stat.txt")
print(string.format("stat size=%d  isFile=%s  isDir=%s",
  info.size, tostring(info.isFile), tostring(info.isDir)))

-- Attempting to stat a non-existent or traversal path raises an error:
local ok3, err3 = pcall(lurek.filesystem.stat, "../../etc/passwd")
print("stat traversal blocked: " .. tostring(not ok3))

-- =============================================================================
-- New in 0.15.0: lurek.filesystem.createTempFile
-- =============================================================================

local tmp1 = lurek.filesystem.createTempFile("demo_")
local tmp2 = lurek.filesystem.createTempFile("demo_")
print("temp1: " .. tmp1)
print("temp2: " .. tmp2)
print("unique: " .. tostring(tmp1 ~= tmp2))

-- =============================================================================
-- STUBS: 3 uncovered lurek.filesystem API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.filesystem.listRecursive --------------------------------
--@api-stub: lurek.filesystem.listRecursive
-- Returns a sorted list of all files under `path`, recursively.
-- Example scenario:
print("Attempting to execute global method listRecursive()")
local status_ok, _ = pcall(function()
    -- Native execution of the listRecursive function
    return lurek.filesystem.listRecursive()
end)
if status_ok then 
    print("listRecursive ran safely with expected parameters.") 
end
lurek.filesystem.listRecursive("assets/hero.png")  -- -> table

-- ---- Stub: lurek.filesystem.mkdir ----------------------------------------
--@api-stub: lurek.filesystem.mkdir
-- Creates a directory (and any missing parents) relative to the game root.
-- Example scenario:
print("Attempting to execute global method mkdir()")
local status_ok, _ = pcall(function()
    -- Native execution of the mkdir function
    return lurek.filesystem.mkdir()
end)
if status_ok then 
    print("mkdir ran safely with expected parameters.") 
end
lurek.filesystem.mkdir("assets/hero.png")

-- ---- Stub: lurek.filesystem.toAbsolutePath -------------------------------
--@api-stub: lurek.filesystem.toAbsolutePath
-- Resolves a path relative to the game root to an absolute OS path string.
-- Example scenario:
print("Attempting to execute global method toAbsolutePath()")
local status_ok, _ = pcall(function()
    -- Native execution of the toAbsolutePath function
    return lurek.filesystem.toAbsolutePath()
end)
if status_ok then 
    print("toAbsolutePath ran safely with expected parameters.") 
end
lurek.filesystem.toAbsolutePath("assets/hero.png")  -- -> string
-- ---- Stub: lurek.filesystem.createTempFile -----------------------------------------------------
--@api-stub: lurek.filesystem.createTempFile
-- Creates an empty temporary file in the `save/` sandbox and returns its
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_createTempFile()
    print('Executing createTempFile')
    print('Example')
end
local _ok, _err = pcall(demo_lurek_filesystem_createTempFile)

-- ---- Stub: lurek.filesystem.stat -----------------------------------------------------
--@api-stub: lurek.filesystem.stat
-- Returns lightweight file statistics for the given path.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_stat()
    print('Executing stat')
    print('Example')
end
local _ok, _err = pcall(demo_lurek_filesystem_stat)

-- ---- Stub: lurek.filesystem.createTempFile -----------------------------------------------------
--@api-stub: lurek.filesystem.createTempFile
-- Creates an empty temporary file in the `save/` sandbox and returns its
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_createTempFile()
    print('Executing createTempFile')
    print('Example')
end
local _ok, _err = pcall(demo_lurek_filesystem_createTempFile)

-- ---- Stub: lurek.filesystem.stat -----------------------------------------------------
--@api-stub: lurek.filesystem.stat
-- Returns lightweight file statistics for the given path.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_filesystem_stat()
    print('Executing stat')
    print('Example')
end
local _ok, _err = pcall(demo_lurek_filesystem_stat)

