-- content/examples/mods.lua
-- Lurek2D lurek.mods API Reference
-- Run with: cargo run -- content/examples/mods

-- =============================================================================
-- STUBS: 40 uncovered lurek.mods API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.mods.newMod ---------------------------------------------
--@api-stub: lurek.mods.newMod
-- Create a Mod descriptor in code to expose a documented extension point
-- without requiring a separate mod.toml on disk.
local hero_mod = lurek.mods.newMod({
    id          = "hero_overhaul",
    name        = "Hero Overhaul",
    version     = "1.2.0",
    author      = "Modder McModface",
    description = "Replaces hero sprites and tweaks movement speed.",
    priority    = 10,
})
print("mod created:", hero_mod:getId())

-- ---- Stub: lurek.mods.newModManager --------------------------------------
--@api-stub: lurek.mods.newModManager
-- Demonstrates the proper usage of lurek.mods.newModManager.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_mods_newModManager()
    local mgr = lurek.mods.newModManager()
    print("ModManager created, mod count:", mgr:getModCount())
end
local _ok, _err = pcall(demo_lurek_mods_newModManager)

-- ---- Stub: lurek.mods.checkApiVersion ------------------------------------
--@api-stub: lurek.mods.checkApiVersion
-- Validate a mod's required engine version before loading it -- fail fast
-- with a friendly message instead of crashing inside a hook.
local compat = lurek.mods.checkApiVersion(hero_mod, "0.5.0")
if compat then
    print("version compatible:", compat.compatible)
else
    print("mod requires a newer engine version")
end

-- -----------------------------------------------------------------------------
-- Mod methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Mod:getId -----------------------------------------------------
--@api-stub: Mod:getId
-- Demonstrates the proper usage of Mod:getId.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getId()
    print("mod id:", hero_mod:getId())  -- "hero_overhaul"
end
local _ok, _err = pcall(demo_Mod_getId)

-- ---- Stub: Mod:getName ---------------------------------------------------
--@api-stub: Mod:getName
-- Demonstrates the proper usage of Mod:getName.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getName()
    print("display name:", hero_mod:getName())  -- "Hero Overhaul"
end
local _ok, _err = pcall(demo_Mod_getName)

-- ---- Stub: Mod:getVersion ------------------------------------------------
--@api-stub: Mod:getVersion
-- Demonstrates the proper usage of Mod:getVersion.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getVersion()
    print("mod version:", hero_mod:getVersion())  -- "1.2.0"
end
local _ok, _err = pcall(demo_Mod_getVersion)

-- ---- Stub: Mod:getAuthor -------------------------------------------------
--@api-stub: Mod:getAuthor
-- Demonstrates the proper usage of Mod:getAuthor.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getAuthor()
    print("author:", hero_mod:getAuthor())
end
local _ok, _err = pcall(demo_Mod_getAuthor)

-- ---- Stub: Mod:getDescription --------------------------------------------
--@api-stub: Mod:getDescription
-- Demonstrates the proper usage of Mod:getDescription.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getDescription()
    print("description:", hero_mod:getDescription())
end
local _ok, _err = pcall(demo_Mod_getDescription)

-- ---- Stub: Mod:getDependencies -------------------------------------------
--@api-stub: Mod:getDependencies
-- Iterate the dependency list to ensure every required mod is loaded
-- before activating this one -- feed into the load-order resolver.
local deps = hero_mod:getDependencies()
print("dependencies:")
for _, dep_id in ipairs(deps) do
    print("  requires:", dep_id)
end

-- ---- Stub: Mod:getPriority -----------------------------------------------
--@api-stub: Mod:getPriority
-- Demonstrates the proper usage of Mod:getPriority.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getPriority()
    print("load priority:", hero_mod:getPriority())  -- 10
end
local _ok, _err = pcall(demo_Mod_getPriority)

-- ---- Stub: Mod:isEnabled -------------------------------------------------
--@api-stub: Mod:isEnabled
-- Guard the load step -- skip disabled mods rather than erroring so
-- the game can continue without optional content.
if hero_mod:isEnabled() then
    print("hero_overhaul is active")
else
    print("hero_overhaul is disabled -- skipping load")
end

-- ---- Stub: Mod:setEnabled ------------------------------------------------
--@api-stub: Mod:setEnabled
-- Toggle from the in-game mod browser without removing the mod from the
-- manager -- disabled mods are preserved but skipped during the load pass.
hero_mod:setEnabled(false)
print("mod enabled:", hero_mod:isEnabled())  -- false
hero_mod:setEnabled(true)

-- ---- Stub: Mod:isLoaded --------------------------------------------------
--@api-stub: Mod:isLoaded
-- Check isLoaded before calling hooks to avoid invoking code that was
-- never initialised (e.g. a mod that failed to load its asset bundle).
if hero_mod:isLoaded() then
    print("hooks are safe to call")
else
    print("mod not yet loaded")
end

-- ---- Stub: Mod:getApiVersion ---------------------------------------------
--@api-stub: Mod:getApiVersion
-- Demonstrates the proper usage of Mod:getApiVersion.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_getApiVersion()
    local api_ver = hero_mod:getApiVersion()
    print("requires API:", api_ver or "any")
end
local _ok, _err = pcall(demo_Mod_getApiVersion)

-- ---- Stub: Mod:setApiVersion ---------------------------------------------
--@api-stub: Mod:setApiVersion
-- Demonstrates the proper usage of Mod:setApiVersion.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_setApiVersion()
    hero_mod:setApiVersion("0.5.0")
    print("api version set to:", hero_mod:getApiVersion())
end
local _ok, _err = pcall(demo_Mod_setApiVersion)

-- ---- Stub: Mod:getCapabilities -------------------------------------------
--@api-stub: Mod:getCapabilities
-- Read declared capabilities to decide which hooks to invoke and which
-- sandbox permissions to grant the mod before it runs.
local caps = hero_mod:getCapabilities()
print("capabilities:")
for _, cap in ipairs(caps) do
    print("  " .. cap)
end

-- ---- Stub: Mod:setCapabilities -------------------------------------------
--@api-stub: Mod:setCapabilities
-- Demonstrates the proper usage of Mod:setCapabilities.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_setCapabilities()
    hero_mod:setCapabilities({ "sprite_override", "stats_patch" })
    print("capabilities set:", #hero_mod:getCapabilities())
end
local _ok, _err = pcall(demo_Mod_setCapabilities)

-- ---- Stub: Mod:getConfigSchema -------------------------------------------
--@api-stub: Mod:getConfigSchema
-- Use the schema to build a settings UI automatically -- each entry
-- describes one config key, its type, and its default value.
local schema = hero_mod:getConfigSchema()
for _, field in ipairs(schema) do
    print(field.key, ":", field.type, "=", field.default)
end

-- ---- Stub: Mod:setConfigSchema -------------------------------------------
--@api-stub: Mod:setConfigSchema
-- Define the schema at registration time so the manager can validate
-- user config and fill in defaults before calling the mod's hooks.
hero_mod:setConfigSchema({
    { key = "speed_multiplier", type = "number",  default = 1.0  },
    { key = "debug_sprites",    type = "boolean", default = false },
})
print("config schema set with", #hero_mod:getConfigSchema(), "fields")

-- ---- Stub: Mod:getHook ---------------------------------------------------
--@api-stub: Mod:getHook
-- Retrieve a specific hook before calling it so you can confirm the mod
-- opted in to this extension point rather than assuming it exists.
local on_spawn = hero_mod:getHook("on_spawn")
if on_spawn then
    print("calling on_spawn hook")
    on_spawn({ entity_id = 1 })
end

-- ---- Stub: Mod:hasHook ---------------------------------------------------
--@api-stub: Mod:hasHook
-- Gate hook dispatch on hasHook() to avoid the getHook() + nil check
-- pattern every time -- keeps the dispatch table lean.
if hero_mod:hasHook("on_damage") then
    print("mod intercepts damage events")
end

-- ---- Stub: Mod:getHookNames ----------------------------------------------
--@api-stub: Mod:getHookNames
-- Enumerate registered hooks in the mod browser or debug output to show
-- exactly which extension points a mod has implemented.
local hooks = hero_mod:getHookNames()
print("registered hooks:")
for _, name in ipairs(hooks) do
    print("  " .. name)
end

-- ---- Stub: Mod:setConfig -------------------------------------------------
--@api-stub: Mod:setConfig
-- Demonstrates the proper usage of Mod:setConfig.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_setConfig()
    hero_mod:setConfig({ speed_multiplier = 1.5, debug_sprites = false })
    print("mod config saved")
end
local _ok, _err = pcall(demo_Mod_setConfig)

-- ---- Stub: Mod:getConfig -------------------------------------------------
--@api-stub: Mod:getConfig
-- Read the active config inside a hook so the mod's behaviour adapts to
-- player settings without hard-coding constants.
local cfg = hero_mod:getConfig()
if cfg then
    print("speed multiplier:", cfg.speed_multiplier)
end

-- ---- Stub: Mod:releaseRefs -----------------------------------------------
--@api-stub: Mod:releaseRefs
-- Demonstrates the proper usage of Mod:releaseRefs.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Mod_releaseRefs()
    hero_mod:releaseRefs()
    print("all references released")
end
local _ok, _err = pcall(demo_Mod_releaseRefs)

-- ---- Stub: ModManager:registerMod ----------------------------------------
--@api-stub: ModManager:registerMod
-- Demonstrates the proper usage of ModManager:registerMod.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_registerMod()
    mgr:registerMod(hero_mod)
    print("mods registered:", mgr:getModCount())
end
local _ok, _err = pcall(demo_ModManager_registerMod)

-- ---- Stub: ModManager:unregisterMod --------------------------------------
--@api-stub: ModManager:unregisterMod
-- Demonstrates the proper usage of ModManager:unregisterMod.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_unregisterMod()
    local removed = mgr:unregisterMod("hero_overhaul")
    print("mod removed:", removed)
end
local _ok, _err = pcall(demo_ModManager_unregisterMod)

-- ---- Stub: ModManager:hasMod ---------------------------------------------
--@api-stub: ModManager:hasMod
-- Guard operations that require a specific mod -- show a friendly error
-- when a dependency is absent rather than crashing inside a hook.
if mgr:hasMod("hero_overhaul") then
    print("hero_overhaul is registered")
else
    print("required mod missing -- aborting load")
end

-- ---- Stub: ModManager:getModCount ----------------------------------------
--@api-stub: ModManager:getModCount
-- Demonstrates the proper usage of ModManager:getModCount.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_getModCount()
    local n = mgr:getModCount()
    print(n, "mod(s) registered")
end
local _ok, _err = pcall(demo_ModManager_getModCount)

-- ---- Stub: ModManager:getAllMods -----------------------------------------
--@api-stub: ModManager:getAllMods
-- Iterate all mods to build the browser list or to run a bulk operation
-- such as export-manifest or enable-all.
local all = mgr:getAllMods()
for _, info in ipairs(all) do
    print(info.id, "-", info.name, "v" .. (info.version or "?"))
end

-- ---- Stub: ModManager:getLoadOrder ---------------------------------------
--@api-stub: ModManager:getLoadOrder
-- Read the resolved load order to display the sequence in the browser
-- and confirm that high-priority mods appear first.
local order = mgr:getLoadOrder()
print("load order:")
for i, info in ipairs(order) do
    print(string.format("  %d. %s (priority %d)", i, info.id, info.priority or 0))
end

-- ---- Stub: ModManager:validateDependencies -------------------------------
--@api-stub: ModManager:validateDependencies
-- Call before the load pass to surface missing dependencies as a readable
-- list rather than a crash during hook execution.
local missing = mgr:validateDependencies()
if #missing > 0 then
    print("missing dependencies:")
    for _, id in ipairs(missing) do print("  " .. id) end
else
    print("all dependencies satisfied")
end

-- ---- Stub: ModManager:hasCircularDependencies ----------------------------
--@api-stub: ModManager:hasCircularDependencies
-- Detect cycles before computing the load order so the engine never enters
-- an infinite sort loop when mod manifests conflict.
if mgr:hasCircularDependencies() then
    print("circular dependency found -- fix manifests before loading")
else
    print("dependency graph is acyclic -- safe to compute load order")
end

-- ---- Stub: ModManager:setLoadOrder ---------------------------------------
--@api-stub: ModManager:setLoadOrder
-- Demonstrates the proper usage of ModManager:setLoadOrder.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_setLoadOrder()
    mgr:setLoadOrder({ "base_game_data", "hero_overhaul", "extra_enemies" })
    print("custom load order applied")
end
local _ok, _err = pcall(demo_ModManager_setLoadOrder)

-- ---- Stub: ModManager:clearLoadOrder -------------------------------------
--@api-stub: ModManager:clearLoadOrder
-- Demonstrates the proper usage of ModManager:clearLoadOrder.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_clearLoadOrder()
    mgr:clearLoadOrder()
    print("load order reset to priority-based sort")
end
local _ok, _err = pcall(demo_ModManager_clearLoadOrder)

-- ---- Stub: ModManager:scanFolder -----------------------------------------
--@api-stub: ModManager:scanFolder
-- Discover and register all mods in a directory in one call -- use this
-- at startup to pick up every mod from the player's mods/ folder.
local found = mgr:scanFolder("mods/")
print("scanned mods/ folder, found:", #found, "mod(s)")
for _, info in ipairs(found) do
    print("  loaded:", info.id)
end

-- ---- Stub: ModManager:getModPath -----------------------------------------
--@api-stub: ModManager:getModPath
-- Demonstrates the proper usage of ModManager:getModPath.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_getModPath()
    local path = mgr:getModPath("hero_overhaul")
    print("mod path:", path or "not found")
end
local _ok, _err = pcall(demo_ModManager_getModPath)

-- ---- Stub: ModManager:markForReload --------------------------------------
--@api-stub: ModManager:markForReload
-- Demonstrates the proper usage of ModManager:markForReload.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_markForReload()
    local queued = mgr:markForReload("hero_overhaul")
    print("queued for reload:", queued)
end
local _ok, _err = pcall(demo_ModManager_markForReload)

-- ---- Stub: ModManager:getReloadQueue -------------------------------------
--@api-stub: ModManager:getReloadQueue
-- Drain the reload queue each frame and reload each mod so file changes
-- take effect immediately during development.
local queue = mgr:getReloadQueue()
if #queue > 0 then
    print("mods pending reload:")
    for _, id in ipairs(queue) do print("  " .. id) end
end

-- ---- Stub: ModManager:clearReloadQueue -----------------------------------
--@api-stub: ModManager:clearReloadQueue
-- Demonstrates the proper usage of ModManager:clearReloadQueue.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ModManager_clearReloadQueue()
    mgr:clearReloadQueue()
    print("reload queue cleared")
end
local _ok, _err = pcall(demo_ModManager_clearReloadQueue)
