-- content/examples/system.lua
-- Lurek2D lurek.system API Reference
-- Run with: cargo run -- content/examples/system

-- =============================================================================
-- STUBS: 26 uncovered lurek.system API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.system.getOS --------------------------------------------
--@api-stub: lurek.system.getOS
-- Returns the host operating system name ('Windows', 'Linux', 'macOS').
-- Example scenario:
print("Attempting to execute global method getOS()")
local status_ok, _ = pcall(function()
    -- Native execution of the getOS function
    return lurek.system.getOS()
end)
if status_ok then 
    print("getOS ran safely with expected parameters.") 
end
lurek.system.getOS()  -- -> string

-- ---- Stub: lurek.system.getVersion ---------------------------------------
--@api-stub: lurek.system.getVersion
-- Returns the Lurek2D engine version string.
-- Example scenario:
print("Attempting to execute global method getVersion()")
local status_ok, _ = pcall(function()
    -- Native execution of the getVersion function
    return lurek.system.getVersion()
end)
if status_ok then 
    print("getVersion ran safely with expected parameters.") 
end
lurek.system.getVersion()  -- -> string

-- ---- Stub: lurek.system.getProcessorCount --------------------------------
--@api-stub: lurek.system.getProcessorCount
-- Returns the number of logical CPU cores available.
-- Example scenario:
print("Attempting to execute global method getProcessorCount()")
local status_ok, _ = pcall(function()
    -- Native execution of the getProcessorCount function
    return lurek.system.getProcessorCount()
end)
if status_ok then 
    print("getProcessorCount ran safely with expected parameters.") 
end
lurek.system.getProcessorCount()  -- -> integer

-- ---- Stub: lurek.system.getMemorySize ------------------------------------
--@api-stub: lurek.system.getMemorySize
-- Returns the total amount of installed system RAM in megabytes.
-- Example scenario:
print("Attempting to execute global method getMemorySize()")
local status_ok, _ = pcall(function()
    -- Native execution of the getMemorySize function
    return lurek.system.getMemorySize()
end)
if status_ok then 
    print("getMemorySize ran safely with expected parameters.") 
end
lurek.system.getMemorySize()  -- -> integer

-- ---- Stub: lurek.system.openURL ------------------------------------------
--@api-stub: lurek.system.openURL
-- Opens a URL in the system's default browser.
-- Example scenario:
print("Attempting to execute global method openURL()")
local status_ok, _ = pcall(function()
    -- Native execution of the openURL function
    return lurek.system.openURL()
end)
if status_ok then 
    print("openURL ran safely with expected parameters.") 
end
lurek.system.openURL(url)  -- -> boolean

-- ---- Stub: lurek.system.getPreferredLocales ------------------------------
--@api-stub: lurek.system.getPreferredLocales
-- Returns an ordered list of the user's preferred locale strings (e.g. 'en-US').
-- Example scenario:
print("Attempting to execute global method getPreferredLocales()")
local status_ok, _ = pcall(function()
    -- Native execution of the getPreferredLocales function
    return lurek.system.getPreferredLocales()
end)
if status_ok then 
    print("getPreferredLocales ran safely with expected parameters.") 
end
lurek.system.getPreferredLocales()  -- -> table

-- ---- Stub: lurek.system.getPowerInfo -------------------------------------
--@api-stub: lurek.system.getPowerInfo
-- Returns battery state, percentage charged, and estimated time remaining.
-- Example scenario:
print("Attempting to execute global method getPowerInfo()")
local status_ok, _ = pcall(function()
    -- Native execution of the getPowerInfo function
    return lurek.system.getPowerInfo()
end)
if status_ok then 
    print("getPowerInfo ran safely with expected parameters.") 
end
lurek.system.getPowerInfo()  -- -> table

-- ---- Stub: lurek.system.getInfo ------------------------------------------
--@api-stub: lurek.system.getInfo
-- Returns a table of system information including OS name, CPU model, and installed RAM.
-- Example scenario:
print("Attempting to execute global method getInfo()")
local status_ok, _ = pcall(function()
    -- Native execution of the getInfo function
    return lurek.system.getInfo()
end)
if status_ok then 
    print("getInfo ran safely with expected parameters.") 
end
lurek.system.getInfo()  -- -> table

-- ---- Stub: lurek.system.getMessage ---------------------------------------
--@api-stub: lurek.system.getMessage
-- Resolves a stable runtime message ID such as 'L001' to its human-readable text.
-- Example scenario:
print("Attempting to execute global method getMessage()")
local status_ok, _ = pcall(function()
    -- Native execution of the getMessage function
    return lurek.system.getMessage()
end)
if status_ok then 
    print("getMessage ran safely with expected parameters.") 
end
lurek.system.getMessage(1)  -- -> string

-- ---- Stub: lurek.system.hasMessage ---------------------------------------
--@api-stub: lurek.system.hasMessage
-- Returns true when the runtime message catalog contains the given stable message ID.
-- Example scenario:
print("Attempting to execute global method hasMessage()")
local status_ok, _ = pcall(function()
    -- Native execution of the hasMessage function
    return lurek.system.hasMessage()
end)
if status_ok then 
    print("hasMessage ran safely with expected parameters.") 
end
lurek.system.hasMessage(1)  -- -> boolean

-- ---- Stub: lurek.system.getMessageCount ----------------------------------
--@api-stub: lurek.system.getMessageCount
-- Returns the total number of message entries loaded into the runtime message catalog.
-- Example scenario:
print("Attempting to execute global method getMessageCount()")
local status_ok, _ = pcall(function()
    -- Native execution of the getMessageCount function
    return lurek.system.getMessageCount()
end)
if status_ok then 
    print("getMessageCount ran safely with expected parameters.") 
end
lurek.system.getMessageCount()  -- -> integer

-- ---- Stub: lurek.system.setClipboardText ---------------------------------
--@api-stub: lurek.system.setClipboardText
-- Replaces the system clipboard contents with the given string.
-- Example scenario:
print("Attempting to execute global method setClipboardText()")
local status_ok, _ = pcall(function()
    -- Native execution of the setClipboardText function
    return lurek.system.setClipboardText()
end)
if status_ok then 
    print("setClipboardText ran safely with expected parameters.") 
end
lurek.system.setClipboardText("Hello, world!")

-- ---- Stub: lurek.system.getClipboardText ---------------------------------
--@api-stub: lurek.system.getClipboardText
-- Returns the current contents of the system clipboard.
-- Example scenario:
print("Attempting to execute global method getClipboardText()")
local status_ok, _ = pcall(function()
    -- Native execution of the getClipboardText function
    return lurek.system.getClipboardText()
end)
if status_ok then 
    print("getClipboardText ran safely with expected parameters.") 
end
lurek.system.getClipboardText()  -- -> string

-- ---- Stub: lurek.system.setDebugOverlay ----------------------------------
--@api-stub: lurek.system.setDebugOverlay
-- Shows or hides the FPS/draw-call debug overlay.
-- Example scenario:
print("Attempting to execute global method setDebugOverlay()")
local status_ok, _ = pcall(function()
    -- Native execution of the setDebugOverlay function
    return lurek.system.setDebugOverlay()
end)
if status_ok then 
    print("setDebugOverlay ran safely with expected parameters.") 
end
lurek.system.setDebugOverlay(true)

-- ---- Stub: lurek.system.getDebugOverlay ----------------------------------
--@api-stub: lurek.system.getDebugOverlay
-- Returns whether the debug overlay is currently visible.
-- Example scenario:
print("Attempting to execute global method getDebugOverlay()")
local status_ok, _ = pcall(function()
    -- Native execution of the getDebugOverlay function
    return lurek.system.getDebugOverlay()
end)
if status_ok then 
    print("getDebugOverlay ran safely with expected parameters.") 
end
lurek.system.getDebugOverlay()

-- ---- Stub: lurek.system.setLogLevel --------------------------------------
--@api-stub: lurek.system.setLogLevel
-- Sets the minimum severity level for runtime log messages.
-- Example scenario:
print("Attempting to execute global method setLogLevel()")
local status_ok, _ = pcall(function()
    -- Native execution of the setLogLevel function
    return lurek.system.setLogLevel()
end)
if status_ok then 
    print("setLogLevel ran safely with expected parameters.") 
end
lurek.system.setLogLevel(level)

-- ---- Stub: lurek.system.getLogLevel --------------------------------------
--@api-stub: lurek.system.getLogLevel
-- Returns the name of the current minimum log level for runtime messages.
-- Example scenario:
print("Attempting to execute global method getLogLevel()")
local status_ok, _ = pcall(function()
    -- Native execution of the getLogLevel function
    return lurek.system.getLogLevel()
end)
if status_ok then 
    print("getLogLevel ran safely with expected parameters.") 
end
lurek.system.getLogLevel()

-- ---- Stub: lurek.system.log ----------------------------------------------
--@api-stub: lurek.system.log
-- Emit a log message from Lua at the specified level.
-- Example scenario:
print("Attempting to execute global method log()")
local status_ok, _ = pcall(function()
    -- Native execution of the log function
    return lurek.system.log()
end)
if status_ok then 
    print("log ran safely with expected parameters.") 
end
lurek.system.log(level, message)

-- ---- Stub: lurek.system.getLastError -------------------------------------
--@api-stub: lurek.system.getLastError
-- Returns the last unhandled error message, or nil.
-- Example scenario:
print("Attempting to execute global method getLastError()")
local status_ok, _ = pcall(function()
    -- Native execution of the getLastError function
    return lurek.system.getLastError()
end)
if status_ok then 
    print("getLastError ran safely with expected parameters.") 
end
lurek.system.getLastError()  -- -> table?

-- ---- Stub: lurek.system.errorSnapshot ------------------------------------
--@api-stub: lurek.system.errorSnapshot
-- Serialises an engine error message to a compact JSON string.
-- Example scenario:
print("Attempting to execute global method errorSnapshot()")
local status_ok, _ = pcall(function()
    -- Native execution of the errorSnapshot function
    return lurek.system.errorSnapshot()
end)
if status_ok then 
    print("errorSnapshot ran safely with expected parameters.") 
end
lurek.system.errorSnapshot("level_complete")  -- -> string

-- ---- Stub: lurek.system.getArch ------------------------------------------
--@api-stub: lurek.system.getArch
-- Returns the CPU architecture string for the current machine.
-- Example scenario:
print("Attempting to execute global method getArch()")
local status_ok, _ = pcall(function()
    -- Native execution of the getArch function
    return lurek.system.getArch()
end)
if status_ok then 
    print("getArch ran safely with expected parameters.") 
end
lurek.system.getArch()  -- -> string

-- ---- Stub: lurek.system.getEnv -------------------------------------------
--@api-stub: lurek.system.getEnv
-- Returns the value of an environment variable, or nil if not set.
-- Example scenario:
print("Attempting to execute global method getEnv()")
local status_ok, _ = pcall(function()
    -- Native execution of the getEnv function
    return lurek.system.getEnv()
end)
if status_ok then 
    print("getEnv ran safely with expected parameters.") 
end
lurek.system.getEnv("hero")

-- ---- Stub: lurek.system.getArgs ------------------------------------------
--@api-stub: lurek.system.getArgs
-- Returns the command-line arguments as a table.
-- Example scenario:
print("Attempting to execute global method getArgs()")
local status_ok, _ = pcall(function()
    -- Native execution of the getArgs function
    return lurek.system.getArgs()
end)
if status_ok then 
    print("getArgs ran safely with expected parameters.") 
end
lurek.system.getArgs()  -- -> table

-- ---- Stub: lurek.system.parseArgs ----------------------------------------
--@api-stub: lurek.system.parseArgs
-- Parses a command-line argument string and returns a structured key/value table.
-- Example scenario:
print("Attempting to execute global method parseArgs()")
local status_ok, _ = pcall(function()
    -- Native execution of the parseArgs function
    return lurek.system.parseArgs()
end)
if status_ok then 
    print("parseArgs ran safely with expected parameters.") 
end
lurek.system.parseArgs([args])  -- -> table

-- ---- Stub: lurek.system.runBatch -----------------------------------------
--@api-stub: lurek.system.runBatch
-- Runs a list of shell commands in parallel and returns immediately without blocking.
-- Example scenario:
print("Attempting to execute global method runBatch()")
local status_ok, _ = pcall(function()
    -- Native execution of the runBatch function
    return lurek.system.runBatch()
end)
if status_ok then 
    print("runBatch ran safely with expected parameters.") 
end
lurek.system.runBatch(tasks, [opts])  -- -> table

-- ---- Stub: lurek.system.getBatchResults ----------------------------------
--@api-stub: lurek.system.getBatchResults
-- Returns the output table from the most recently completed runBatch call.
-- Example scenario:
print("Attempting to execute global method getBatchResults()")
local status_ok, _ = pcall(function()
    -- Native execution of the getBatchResults function
    return lurek.system.getBatchResults()
end)
if status_ok then 
    print("getBatchResults ran safely with expected parameters.") 
end
lurek.system.getBatchResults(results)  -- -> integer
