-- content/examples/thread.lua
-- Lurek2D lurek.thread API Reference
-- Run with: cargo run -- content/examples/thread

-- =============================================================================
-- STUBS: 37 uncovered lurek.thread API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.thread.newThread ----------------------------------------
--@api-stub: lurek.thread.newThread
-- Run heavy work (pathfinding, world gen, parsing) off the main Lua VM so the
-- game loop never stalls waiting for a long computation to finish.
local worker_code = [[
    local ch_in  = lurek.thread.getChannel("work_in")
    local ch_out = lurek.thread.getChannel("work_out")
    while true do
        local job = ch_in:demand()
        if job == nil then break end
        ch_out:push(job * job)  -- square the number as a demo
    end
]]
local worker = lurek.thread.newThread(worker_code)

-- ---- Stub: lurek.thread.newChannel ---------------------------------------
--@api-stub: lurek.thread.newChannel
-- Create a private, unnamed channel when only the current script needs it --
-- useful for one-off producer/consumer pairs inside a single module.
local ch = lurek.thread.newChannel()
ch:push(100)
print("channel created, items:", ch:getCount())

-- ---- Stub: lurek.thread.getChannel ---------------------------------------
--@api-stub: lurek.thread.getChannel
-- Demonstrates the proper usage of lurek.thread.getChannel.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_lurek_thread_getChannel()
    local results_ch = lurek.thread.getChannel("results")
    print("named channel 'results' retrieved, items:", results_ch:getCount())
end
local _ok, _err = pcall(demo_lurek_thread_getChannel)

-- ---- Stub: lurek.thread.newPool ------------------------------------------
--@api-stub: lurek.thread.newPool
-- Spawn N identical worker VMs to process a queue of jobs in parallel --
-- ideal for batch tile loading, parallel path-finding, or noise generation.
local tile_worker = [[
    local inp = lurek.thread.getChannel("tiles_in")
    local out = lurek.thread.getChannel("tiles_out")
    while true do
        local id = inp:demand()
        if id == nil then break end
        out:push({ id = id, data = "generated" })
    end
]]
local pool = lurek.thread.newPool(4, tile_worker)
print("pool of 4 tile-gen workers created")

-- ---- Stub: lurek.thread.async --------------------------------------------
--@api-stub: lurek.thread.async
-- Fire-and-forget one-shot background computation -- the returned Promise
-- lets the main loop stay responsive while the work runs in the background.
local code = "return { sum = 1 + 2 + 3 + 4 + 5 }"
local promise = lurek.thread.async(code, {})
print("async computation started, promise:", promise:type())

-- -----------------------------------------------------------------------------
-- Channel methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Channel:type --------------------------------------------------
--@api-stub: Channel:type
-- Demonstrates the proper usage of Channel:type.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_type()
    print(ch:type())  -- "Channel"
end
local _ok, _err = pcall(demo_Channel_type)

-- ---- Stub: Channel:typeOf ------------------------------------------------
--@api-stub: Channel:typeOf
-- Demonstrates the proper usage of Channel:typeOf.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_typeOf()
    print(ch:typeOf("Channel"))  -- true
    print(ch:typeOf("Thread"))   -- false
end
local _ok, _err = pcall(demo_Channel_typeOf)

-- ---- Stub: Channel:push --------------------------------------------------
--@api-stub: Channel:push
-- Demonstrates the proper usage of Channel:push.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_push()
    local count = ch:push("tile_job_42")
    print("items in channel after push:", count)
end
local _ok, _err = pcall(demo_Channel_push)

-- ---- Stub: Channel:pop ---------------------------------------------------
--@api-stub: Channel:pop
-- Non-blocking: returns nil immediately if the channel is empty, so call
-- this from the main-loop process callback to drain results without stalling.
local result = ch:pop()
if result ~= nil then
    print("got result from worker:", result)
end

-- ---- Stub: Channel:peek --------------------------------------------------
--@api-stub: Channel:peek
-- Demonstrates the proper usage of Channel:peek.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_peek()
    local front = ch:peek()
    print("next value (not removed):", front)
end
local _ok, _err = pcall(demo_Channel_peek)

-- ---- Stub: Channel:demand ------------------------------------------------
--@api-stub: Channel:demand
-- Blocking pop with optional timeout -- use inside a worker VM where you
-- want the thread to sleep until a job arrives rather than busy-spinning.
local job = ch:demand(5.0)  -- wait up to 5 seconds
if job == nil then
    print("no job arrived within timeout")
else
    print("job received:", job)
end

-- ---- Stub: Channel:getCount ----------------------------------------------
--@api-stub: Channel:getCount
-- Demonstrates the proper usage of Channel:getCount.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_getCount()
    print("pending jobs:", ch:getCount())
end
local _ok, _err = pcall(demo_Channel_getCount)

-- ---- Stub: Channel:clear -------------------------------------------------
--@api-stub: Channel:clear
-- Flush the channel before reuse -- call this when restarting a level to
-- discard stale results left over from the previous session.
print("items before clear:", ch:getCount())
ch:clear()
print("items after clear:", ch:getCount())  -- 0

-- ---- Stub: Channel:supply ------------------------------------------------
--@api-stub: Channel:supply
-- Demonstrates the proper usage of Channel:supply.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_supply()
    ch:supply("result_99")  -- blocks until there is room
    print("value supplied to channel")
end
local _ok, _err = pcall(demo_Channel_supply)

-- ---- Stub: Channel:pushTable ---------------------------------------------
--@api-stub: Channel:pushTable
-- Demonstrates the proper usage of Channel:pushTable.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Channel_pushTable()
    local job_count = ch:pushTable({ type = "generate_tile", x = 5, y = 3 })
    print("table job queued, queue depth:", job_count)
end
local _ok, _err = pcall(demo_Channel_pushTable)

-- ---- Stub: Channel:popTable ----------------------------------------------
--@api-stub: Channel:popTable
-- Receive a structured result from a worker -- always pair with pushTable()
-- on the sender side so the data survives the serialisation round-trip.
local tile_data = ch:popTable()
if tile_data then
    print("tile received: x =", tile_data.x, "y =", tile_data.y)
end

-- ---- Stub: Channel:pushBytes ---------------------------------------------
--@api-stub: Channel:pushBytes
-- Send raw binary data (e.g. compressed chunk data) to a worker without
-- the overhead of Lua table serialisation.
local raw = "\0\1\2\3\4\5"
local depth = ch:pushBytes(raw)
print("binary blob pushed, queue depth:", depth)

-- ---- Stub: Channel:popBytes ----------------------------------------------
--@api-stub: Channel:popBytes
-- Receive the raw byte blob pushed by the producer side -- returned as a
-- Lua string so you can pass it to a decompressor or binary parser.
local blob = ch:popBytes()
if blob then
    print("received", #blob, "bytes")
end

-- -----------------------------------------------------------------------------
-- Promise methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Promise:type --------------------------------------------------
--@api-stub: Promise:type
-- Demonstrates the proper usage of Promise:type.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Promise_type()
    print(promise:type())  -- "Promise"
end
local _ok, _err = pcall(demo_Promise_type)

-- ---- Stub: Promise:typeOf ------------------------------------------------
--@api-stub: Promise:typeOf
-- Demonstrates the proper usage of Promise:typeOf.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_Promise_typeOf()
    print(promise:typeOf("Promise"))  -- true
end
local _ok, _err = pcall(demo_Promise_typeOf)

-- ---- Stub: Promise:isDone ------------------------------------------------
--@api-stub: Promise:isDone
-- Poll this from the main-loop process callback each frame -- the result
-- is ready only when isDone() returns true.
if promise:isDone() then
    local r = promise:result()
    print("async task finished, result:", r)
end

-- ---- Stub: Promise:result ------------------------------------------------
--@api-stub: Promise:result
-- Call only after isDone() returns true -- returns nil if the task errored
-- (check getError() in that case) or hasn't finished yet.
local res = promise:result()
if res ~= nil then
    print("computed sum:", res.sum)
end

-- ---- Stub: Promise:getError ----------------------------------------------
--@api-stub: Promise:getError
-- Always check getError() after isDone() to catch worker crashes and log
-- them before the promise is garbage-collected.
local err = promise:getError()
if err then
    print("async task failed:", err)
end

-- -----------------------------------------------------------------------------
-- ThreadHandle methods
-- -----------------------------------------------------------------------------

-- ---- Stub: ThreadHandle:type ---------------------------------------------
--@api-stub: ThreadHandle:type
-- Demonstrates the proper usage of ThreadHandle:type.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadHandle_type()
    print(worker:type())  -- "Thread"
end
local _ok, _err = pcall(demo_ThreadHandle_type)

-- ---- Stub: ThreadHandle:typeOf -------------------------------------------
--@api-stub: ThreadHandle:typeOf
-- Demonstrates the proper usage of ThreadHandle:typeOf.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadHandle_typeOf()
    print(worker:typeOf("Thread"))  -- true
end
local _ok, _err = pcall(demo_ThreadHandle_typeOf)

-- ---- Stub: ThreadHandle:start --------------------------------------------
--@api-stub: ThreadHandle:start
-- Demonstrates the proper usage of ThreadHandle:start.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadHandle_start()
    worker:start()
    print("worker thread launched")
end
local _ok, _err = pcall(demo_ThreadHandle_start)

-- ---- Stub: ThreadHandle:wait ---------------------------------------------
--@api-stub: ThreadHandle:wait
-- Demonstrates the proper usage of ThreadHandle:wait.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadHandle_wait()
    worker:wait()
    print("worker finished")
end
local _ok, _err = pcall(demo_ThreadHandle_wait)

-- ---- Stub: ThreadHandle:isRunning ----------------------------------------
--@api-stub: ThreadHandle:isRunning
-- Poll this from the main loop to decide when to drain the output channel
-- or to display a progress indicator during a long background operation.
if worker:isRunning() then
    print("worker still running...")
else
    print("worker has stopped")
end

-- ---- Stub: ThreadHandle:getError -----------------------------------------
--@api-stub: ThreadHandle:getError
-- Always check getError() after a worker stops unexpectedly to surface
-- crashes that would otherwise silently discard results.
local err = worker:getError()
if err then
    print("worker failed:", err)
end

-- -----------------------------------------------------------------------------
-- ThreadPool methods
-- -----------------------------------------------------------------------------

-- ---- Stub: ThreadPool:type -----------------------------------------------
--@api-stub: ThreadPool:type
-- Demonstrates the proper usage of ThreadPool:type.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadPool_type()
    print(pool:type())  -- "ThreadPool"
end
local _ok, _err = pcall(demo_ThreadPool_type)

-- ---- Stub: ThreadPool:typeOf ---------------------------------------------
--@api-stub: ThreadPool:typeOf
-- Demonstrates the proper usage of ThreadPool:typeOf.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadPool_typeOf()
    print(pool:typeOf("ThreadPool"))  -- true
end
local _ok, _err = pcall(demo_ThreadPool_typeOf)

-- ---- Stub: ThreadPool:submit ---------------------------------------------
--@api-stub: ThreadPool:submit
-- Send a job into the pool's shared input channel -- workers pick up jobs
-- in FIFO order; if all workers are busy the call returns immediately.
for i = 1, 16 do
    pool:submit({ tile_x = i, tile_y = 1 })
end
print("16 tile-generation jobs submitted to the pool")

-- ---- Stub: ThreadPool:collect --------------------------------------------
--@api-stub: ThreadPool:collect
-- Non-blocking drain of completed results -- call in the main-loop process
-- callback each frame to integrate finished work without stalling.
local result = pool:collect()
if result then
    print("tile ready: x =", result.tile_x)
end

-- ---- Stub: ThreadPool:size -----------------------------------------------
--@api-stub: ThreadPool:size
-- Read pool size to decide how many jobs to batch-submit to keep all
-- workers busy without swamping the input channel.
local workers = pool:size()
print("pool has", workers, "worker threads")
print("submit batches of", workers * 4, "jobs for optimal throughput")

-- ---- Stub: ThreadPool:join -----------------------------------------------
--@api-stub: ThreadPool:join
-- Demonstrates the proper usage of ThreadPool:join.
-- This example encapsulates the logic to ensure clean execution and state management.
local function demo_ThreadPool_join()
    pool:join()
    print("all pool workers finished -- world generation complete")
end
local _ok, _err = pcall(demo_ThreadPool_join)

-- ---- Stub: ThreadPool:getInputChannel ------------------------------------
--@api-stub: ThreadPool:getInputChannel
-- Access the raw input channel to perform batch pushTable() calls or to
-- share the channel reference with a producer that lives in another module.
local inp = pool:getInputChannel()
inp:pushTable({ task = "generate", seed = 42 })
print("input channel queue depth:", inp:getCount())

-- ---- Stub: ThreadPool:getOutputChannel -----------------------------------
--@api-stub: ThreadPool:getOutputChannel
-- Access the raw output channel to call popTable() or drain all pending
-- results in a loop without using the convenience collect() wrapper.
local out = pool:getOutputChannel()
while out:getCount() > 0 do
    local item = out:popTable()
    print("worker result:", item)
end
