--- Unit tests for lurek.dsp core API.

local T = lurek.test

T.group("lurek.dsp existence", function()
    T.test("lurek.dsp table exists", function()
        T.assertNotNil(lurek.dsp)
    end)

    T.test("lurek.dsp.newEffectParams exists", function()
        T.assertNotNil(lurek.dsp.newEffectParams)
        T.assertEqual(type(lurek.dsp.newEffectParams), "function")
    end)

    T.test("lurek.dsp.processOffline exists", function()
        T.assertNotNil(lurek.dsp.processOffline)
        T.assertEqual(type(lurek.dsp.processOffline), "function")
    end)

    T.test("lurek.dsp.normalize exists", function()
        T.assertNotNil(lurek.dsp.normalize)
        T.assertEqual(type(lurek.dsp.normalize), "function")
    end)

    T.test("lurek.dsp.waveformToPng exists", function()
        T.assertNotNil(lurek.dsp.waveformToPng)
        T.assertEqual(type(lurek.dsp.waveformToPng), "function")
    end)

    T.test("lurek.dsp.spectrogramToPng exists", function()
        T.assertNotNil(lurek.dsp.spectrogramToPng)
        T.assertEqual(type(lurek.dsp.spectrogramToPng), "function")
    end)
end)

T.group("lurek.dsp.newEffectParams", function()
    T.test("creates params with correct fields", function()
        local p = lurek.dsp.newEffectParams("lowpass", 1000, 0.7, 0)
        T.assertEqual(p.type, "lowpass")
        T.assertEqual(p.p1, 1000)
        T.assertEqual(p.p2, 0.7)
        T.assertEqual(p.p3, 0)
    end)

    T.test("supports all effect types", function()
        local types = {
            "lowpass", "highpass", "bandpass", "notch",
            "reverb", "delay", "chorus", "flanger",
            "distortion", "bitcrush", "compressor", "limiter",
            "tremolo", "vibrato", "phaser", "gain",
        }
        for _, t in ipairs(types) do
            local p = lurek.dsp.newEffectParams(t, 1, 2, 3)
            T.assertEqual(p.type, t)
        end
    end)
end)

T.group("lurek.dsp new filter/analyze functions exist", function()
    T.test("applyLowpass exists", function()
        T.assertNotNil(lurek.dsp.applyLowpass)
        T.assertEqual(type(lurek.dsp.applyLowpass), "function")
    end)
    T.test("applyHighpass exists", function()
        T.assertNotNil(lurek.dsp.applyHighpass)
        T.assertEqual(type(lurek.dsp.applyHighpass), "function")
    end)
    T.test("applyBandpass exists", function()
        T.assertNotNil(lurek.dsp.applyBandpass)
        T.assertEqual(type(lurek.dsp.applyBandpass), "function")
    end)
    T.test("applyGain exists", function()
        T.assertNotNil(lurek.dsp.applyGain)
        T.assertEqual(type(lurek.dsp.applyGain), "function")
    end)
    T.test("analyzeRms exists", function()
        T.assertNotNil(lurek.dsp.analyzeRms)
        T.assertEqual(type(lurek.dsp.analyzeRms), "function")
    end)
    T.test("analyzePeak exists", function()
        T.assertNotNil(lurek.dsp.analyzePeak)
        T.assertEqual(type(lurek.dsp.analyzePeak), "function")
    end)
    T.test("analyzeFft exists", function()
        T.assertNotNil(lurek.dsp.analyzeFft)
        T.assertEqual(type(lurek.dsp.analyzeFft), "function")
    end)
    T.test("addEffectToBus exists", function()
        T.assertNotNil(lurek.dsp.addEffectToBus)
        T.assertEqual(type(lurek.dsp.addEffectToBus), "function")
    end)
    T.test("removeEffectFromBus exists", function()
        T.assertNotNil(lurek.dsp.removeEffectFromBus)
        T.assertEqual(type(lurek.dsp.removeEffectFromBus), "function")
    end)
    T.test("setEffectParam exists", function()
        T.assertNotNil(lurek.dsp.setEffectParam)
        T.assertEqual(type(lurek.dsp.setEffectParam), "function")
    end)
end)

T.group("lurek.dsp.analyzeRms", function()
    T.test("returns a number in [0,1] for a sine wave", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        local rms = lurek.dsp.analyzeRms(sd)
        T.assertEqual(type(rms), "number")
        T.assertEqual(rms >= 0.0, true)
        T.assertEqual(rms <= 1.0, true)
    end)
end)

T.group("lurek.dsp.analyzePeak", function()
    T.test("returns a number in [0,1] for a sine wave", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        local peak = lurek.dsp.analyzePeak(sd)
        T.assertEqual(type(peak), "number")
        T.assertEqual(peak >= 0.0, true)
        T.assertEqual(peak <= 1.0, true)
    end)
    T.test("applyGain increases peak when gain > 1", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.4)
        local before = lurek.dsp.analyzePeak(sd)
        lurek.dsp.applyGain(sd, 2.0)
        local after = lurek.dsp.analyzePeak(sd)
        T.assertEqual(after > before, true)
    end)
end)

T.group("lurek.dsp.analyzeFft", function()
    T.test("returns a table of bins with frequency and magnitude fields", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        local bins = lurek.dsp.analyzeFft(sd, 16)
        T.assertEqual(type(bins), "table")
        T.assertEqual(#bins > 0, true)
        local first = bins[1]
        T.assertEqual(type(first.frequency), "number")
        T.assertEqual(type(first.magnitude), "number")
    end)
end)

T.group("lurek.dsp apply filters", function()
    T.test("applyLowpass does not error on LSoundData", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        lurek.dsp.applyLowpass(sd, 1000)
        T.assertEqual(true, true)
    end)
    T.test("applyHighpass does not error on LSoundData", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        lurek.dsp.applyHighpass(sd, 100)
        T.assertEqual(true, true)
    end)
    T.test("applyBandpass does not error on LSoundData", function()
        local sd = lurek.audio.newSineWave(440, 0.1, 44100, 0.5)
        lurek.dsp.applyBandpass(sd, 200, 2000)
        T.assertEqual(true, true)
    end)
end)

T.group("lurek.dsp bus effects", function()
    T.test("addEffectToBus returns a number effect id", function()
        lurek.audio.create_bus("test_dsp_bus")
        local eid = lurek.dsp.addEffectToBus("test_dsp_bus", "lowpass")
        T.assertEqual(type(eid), "number")
    end)
    T.test("removeEffectFromBus returns true", function()
        lurek.audio.create_bus("test_dsp_remove_bus")
        local eid = lurek.dsp.addEffectToBus("test_dsp_remove_bus", "lowpass")
        local ok = lurek.dsp.removeEffectFromBus("test_dsp_remove_bus", eid)
        T.assertEqual(ok, true)
    end)
    T.test("setEffectParam returns true for valid cutoff param", function()
        lurek.audio.create_bus("test_dsp_param_bus")
        local eid = lurek.dsp.addEffectToBus("test_dsp_param_bus", "lowpass")
        local ok = lurek.dsp.setEffectParam("test_dsp_param_bus", eid, "cutoff", 500.0)
        T.assertEqual(ok, true)
    end)
    T.test("addEffectToBus errors for unknown bus", function()
        local ok = pcall(function()
            lurek.dsp.addEffectToBus("nonexistent_bus_xyz_dsp", "lowpass")
        end)
        T.assertEqual(ok, false)
    end)
end)

test_summary()
