-- tests/lua/unit/test_loot_unit.lua
-- lurek.math.newLootTable and lurek.math.newPityTracker unit tests (TST-06)

local T = ...
local math = lurek.math

T.group("lurek.math.newLootTable", function()
    T.test("creates an empty table", function()
        local lt = math.newLootTable()
        T.assert_equal(lt:entryCount(), 0)
    end)

    T.test("add / entryCount", function()
        local lt = math.newLootTable()
        lt:add("sword",  10.0)
        lt:add("shield",  5.0)
        T.assert_equal(lt:entryCount(), 2)
    end)

    T.test("sample returns valid id after build", function()
        local lt = math.newLootTable(42)
        lt:add("gold",  80.0)
        lt:add("gem",   20.0)
        lt:build()
        local entry = lt:sample()
        T.assert_not_nil(entry)
        T.assert_true(entry.id == "gold" or entry.id == "gem",
            "expected gold or gem, got: " .. tostring(entry and entry.id))
    end)

    T.test("sampleN returns n results", function()
        local lt = math.newLootTable(1)
        lt:add("apple", 1.0)
        lt:add("banana", 1.0)
        lt:build()
        local results = lt:sampleN(5)
        T.assert_equal(#results, 5)
    end)

    T.test("sampleUnique returns no duplicates", function()
        local lt = math.newLootTable(99)
        lt:add("a", 1.0)
        lt:add("b", 1.0)
        lt:add("c", 1.0)
        lt:build()
        local results = lt:sampleUnique(3)
        T.assert_equal(#results, 3)
        local seen = {}
        for _, e in ipairs(results) do
            T.assert_nil(seen[e.id], "duplicate id: " .. e.id)
            seen[e.id] = true
        end
    end)

    T.test("remove decreases entryCount", function()
        local lt = math.newLootTable()
        lt:add("x", 5.0)
        lt:add("y", 5.0)
        local removed = lt:remove("x")
        T.assert_true(removed)
        T.assert_equal(lt:entryCount(), 1)
    end)

    T.test("setWeight updates weight", function()
        local lt = math.newLootTable()
        lt:add("rare", 1.0)
        local ok = lt:setWeight("rare", 50.0)
        T.assert_true(ok)
    end)

    T.test("setSeed makes results deterministic", function()
        local function make_and_sample(seed)
            local lt = math.newLootTable(seed)
            lt:add("head",  50.0)
            lt:add("tail",  50.0)
            lt:build()
            return lt:sample().id
        end
        local a = make_and_sample(7)
        local b = make_and_sample(7)
        T.assert_equal(a, b)
    end)

    T.test("typeOf returns LLootTable", function()
        local lt = math.newLootTable()
        T.assert_true(lt:typeOf("LLootTable"))
        T.assert_true(lt:typeOf("LObject"))
        T.assert_false(lt:typeOf("LSprite"))
    end)
end)

T.group("lurek.math.newPityTracker", function()
    T.test("creates tracker with zero counter", function()
        local pt = math.newPityTracker("rare", 5)
        T.assert_equal(pt:counter(), 0)
        T.assert_false(pt:isPrimed())
    end)

    T.test("primes after threshold misses", function()
        local pt = math.newPityTracker("rare", 3)
        pt:notice("common")
        pt:notice("common")
        T.assert_false(pt:isPrimed())
        pt:notice("common")
        T.assert_true(pt:isPrimed())
    end)

    T.test("resets on target hit", function()
        local pt = math.newPityTracker("rare", 3)
        pt:notice("common")
        pt:notice("common")
        pt:notice("common") -- primed
        pt:notice("rare")   -- hit resets
        T.assert_false(pt:isPrimed())
        T.assert_equal(pt:counter(), 0)
    end)

    T.test("reset() clears counter and primed", function()
        local pt = math.newPityTracker("epic", 2)
        pt:notice("trash")
        pt:notice("trash")
        T.assert_true(pt:isPrimed())
        pt:reset()
        T.assert_false(pt:isPrimed())
        T.assert_equal(pt:counter(), 0)
    end)

    T.test("export / import round-trips state", function()
        local pt = math.newPityTracker("gold", 4)
        pt:notice("silver")
        pt:notice("silver")
        local blob = pt:export()
        T.assert_not_nil(blob)
        local pt2 = math.newPityTracker("gold", 4)
        pt2:import(blob)
        T.assert_equal(pt2:counter(), 2)
    end)

    T.test("typeOf returns LPityTracker", function()
        local pt = math.newPityTracker("x", 1)
        T.assert_true(pt:typeOf("LPityTracker"))
        T.assert_true(pt:typeOf("LObject"))
        T.assert_false(pt:typeOf("LBeatClock"))
    end)
end)
