-- Lurek2D REPL API Unit Tests
-- Headless-safe: exercises release-safe lurek.repl without window, render, or input.

describe("lurek.repl module", function()
    it("exists as a table", function()
        expect_type("table", lurek.repl)
        expect_type("function", lurek.repl.new)
    end)
end)

describe("LReplSession", function()
    -- @covers lurek.repl.new
    it("evaluates expressions", function()
        local repl = lurek.repl.new(8)
        expect_equal("4", repl:eval("2 + 2"))
    end)

    it("evaluates statements and keeps Lua globals", function()
        local repl = lurek.repl.new(8)
        expect_equal("(ok)", repl:eval("repl_answer = 41"))
        expect_equal("42", repl:eval("repl_answer + 1"))
    end)

    -- @covers LReplSession:len
    it("keeps bounded history", function()
        local repl = lurek.repl.new(2)
        repl:eval("1")
        repl:eval("2")
        repl:eval("3")
        local history = repl:history()
        expect_equal(2, #history)
        expect_equal("2", history[1])
        expect_equal("3", history[2])
        expect_equal(2, repl:len())
    end)

    it("supports commands", function()
        local repl = lurek.repl.new(8)
        expect_contains(repl:eval(":help"), ":load")
        expect_equal("(quit)", repl:eval(":quit"))
        expect_equal("(cleared)", repl:eval(":clear"))
        expect_equal(0, repl:len())
    end)

    it("returns completions", function()
        local repl = lurek.repl.new(8)
        local completions = repl:complete("lurek.re")
        expect_true(#completions >= 1)
    end)

    it(":reset returns reset confirmation and clears history", function()
        local repl = lurek.repl.new(8)
        repl:eval("1 + 1")
        repl:eval("2 + 2")
        local result = repl:eval(":reset")
        expect_equal("(reset)", result)
        expect_equal(0, repl:len())
    end)

    it(":load nonexistent file returns error result", function()
        local repl = lurek.repl.new(8)
        local result = repl:eval(":load __nonexistent_repl_test_file__.lua")
        expect_contains(result, "error:")
    end)

    it(":load with no path returns error result", function()
        local repl = lurek.repl.new(8)
        local result = repl:eval(":load")
        expect_contains(result, "error:")
    end)

    it("reports type identity", function()
        local repl = lurek.repl.new(8)
        expect_equal("LReplSession", repl:type())
        expect_true(repl:typeOf("LReplSession"))
        expect_true(repl:typeOf("Object"))
        expect_false(repl:typeOf("Other"))
    end)
end)

test_summary()
