-- tests/lua/unit/test_tween_chain_unit.lua
-- lurek.tween.newChain unit tests (TST-06)

local T = ...
local tween = lurek.tween

T.group("lurek.tween.newChain", function()
    T.test("creates empty chain", function()
        local ch = tween.newChain()
        T.assert_equal(ch:len(), 0)
        T.assert_false(ch:isFinished())
        T.assert_false(ch:isLooping())
    end)

    T.test("push adds step and returns 1-based index", function()
        local ch = tween.newChain()
        local idx = ch:push({ from = 0, to = 1, duration = 1.0 })
        T.assert_equal(ch:len(), 1)
        -- push returns 0-based Rust idx; we expose +1 for Lua but push returns raw
        T.assert_not_nil(idx)
    end)

    T.test("value at start is from value", function()
        local ch = tween.newChain()
        ch:push({ from = 5.0, to = 10.0, duration = 2.0 })
        T.assert_true(math.abs(ch:value() - 5.0) < 1e-6)
    end)

    T.test("tick advances and returns events on completion", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 1.0, label = "done" })
        local events = ch:tick(1.5)
        T.assert_equal(#events, 1)
        T.assert_equal(events[1].label, "done")
        T.assert_true(ch:isFinished())
    end)

    T.test("intermediate tick does not finish chain", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 2.0 })
        ch:tick(0.5)
        T.assert_false(ch:isFinished())
        local v = ch:value()
        T.assert_true(v > 0.0 and v < 1.0)
    end)

    T.test("cursor tracks active step (1-based)", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 0.5 })
        ch:push({ from = 1.0, to = 2.0, duration = 0.5 })
        T.assert_equal(ch:cursor(), 1)
        ch:tick(0.6) -- crosses first step
        T.assert_equal(ch:cursor(), 2)
    end)

    T.test("reset goes back to step 1", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 0.5 })
        ch:push({ from = 1.0, to = 2.0, duration = 0.5 })
        ch:tick(0.6)
        ch:reset()
        T.assert_equal(ch:cursor(), 1)
        T.assert_false(ch:isFinished())
    end)

    T.test("jumpTo changes cursor", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 1.0 })
        ch:push({ from = 1.0, to = 2.0, duration = 1.0 })
        ch:jumpTo(2)
        T.assert_equal(ch:cursor(), 2)
    end)

    T.test("setLooping loops chain after last step", function()
        local ch = tween.newChain(true)
        T.assert_true(ch:isLooping())
        ch:push({ from = 0.0, to = 1.0, duration = 0.5 })
        ch:tick(1.0)
        T.assert_false(ch:isFinished(), "looping chain must not finish")
        T.assert_equal(ch:cursor(), 1, "should wrap to step 1")
    end)

    T.test("clear removes all steps", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 1.0 })
        ch:clear()
        T.assert_equal(ch:len(), 0)
    end)

    T.test("multi-step span fires multiple events in one tick", function()
        local ch = tween.newChain()
        ch:push({ from = 0.0, to = 1.0, duration = 0.1, label = "a" })
        ch:push({ from = 1.0, to = 2.0, duration = 0.1, label = "b" })
        local events = ch:tick(0.5)  -- both steps complete
        T.assert_equal(#events, 2)
        T.assert_equal(events[1].label, "a")
        T.assert_equal(events[2].label, "b")
    end)

    T.test("typeOf returns LTweenChain", function()
        local ch = tween.newChain()
        T.assert_true(ch:typeOf("LTweenChain"))
        T.assert_true(ch:typeOf("LObject"))
        T.assert_false(ch:typeOf("LTween"))
    end)
end)
