require("tests/lua/init")

describe("lurek.network server/client roles", function()
    it("should have newServer function", function()
        expect_equal(type(lurek.network.newServer), "function")
    end)

    it("should have newClient function", function()
        expect_equal(type(lurek.network.newClient), "function")
    end)

    it("should create a server with getRole() == 'server'", function()
        local server = lurek.network.newServer({ port = 19100 })
        expect_equal(server:getRole(), "server")
        expect_equal(server:isServer(), true)
        expect_equal(server:isClient(), false)
        server:destroy()
    end)

    it("should create a generic host with getRole() == 'host'", function()
        local host = lurek.network.newHost({ addr = "0.0.0.0:0" })
        expect_equal(host:getRole(), "host")
        expect_equal(host:isServer(), false)
        expect_equal(host:isClient(), false)
        host:destroy()
    end)

    it("server isDestroyed should be false before destroy", function()
        local server = lurek.network.newServer({ port = 19101 })
        expect_equal(server:isDestroyed(), false)
        server:destroy()
        expect_equal(server:isDestroyed(), true)
    end)

    it("should expose updated constants", function()
        expect_equal(lurek.network.MAX_PEERS, 4096)
        expect_equal(lurek.network.DEFAULT_PEERS, 16)
        expect_equal(lurek.network.DEFAULT_CHANNELS, 2)
        expect_equal(lurek.network.MAX_CHANNELS, 255)
    end)
end)

test_summary()
