require("tests/lua/init")

describe("lurek.network.pack / unpack", function()
    it("should exist as functions", function()
        expect_equal(type(lurek.network.pack), "function")
        expect_equal(type(lurek.network.unpack), "function")
    end)

    it("should round-trip nil", function()
        local packed = lurek.network.pack(nil)
        expect_equal(type(packed), "string")
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, nil)
    end)

    it("should round-trip boolean true", function()
        local packed = lurek.network.pack(true)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, true)
    end)

    it("should round-trip boolean false", function()
        local packed = lurek.network.pack(false)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, false)
    end)

    it("should round-trip integers", function()
        local packed = lurek.network.pack(42)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, 42)
    end)

    it("should round-trip negative integers", function()
        local packed = lurek.network.pack(-100)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, -100)
    end)

    it("should round-trip zero", function()
        local packed = lurek.network.pack(0)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, 0)
    end)

    it("should round-trip floats", function()
        local packed = lurek.network.pack(3.14)
        local unpacked = lurek.network.unpack(packed)
        expect_near(unpacked, 3.14, 0.001)
    end)

    it("should round-trip strings", function()
        local packed = lurek.network.pack("hello world")
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, "hello world")
    end)

    it("should round-trip empty string", function()
        local packed = lurek.network.pack("")
        local unpacked = lurek.network.unpack(packed)
        expect_equal(unpacked, "")
    end)

    it("should round-trip arrays (sequential tables)", function()
        local input = { 1, 2, 3, "four", true }
        local packed = lurek.network.pack(input)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(type(unpacked), "table")
        expect_equal(unpacked[1], 1)
        expect_equal(unpacked[2], 2)
        expect_equal(unpacked[3], 3)
        expect_equal(unpacked[4], "four")
        expect_equal(unpacked[5], true)
    end)

    it("should round-trip maps (string-keyed tables)", function()
        local input = { name = "Alice", score = 100 }
        local packed = lurek.network.pack(input)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(type(unpacked), "table")
        expect_equal(unpacked.name, "Alice")
        expect_equal(unpacked.score, 100)
    end)

    it("should round-trip nested tables", function()
        local input = { pos = { x = 10, y = 20 }, tags = { "a", "b" } }
        local packed = lurek.network.pack(input)
        local unpacked = lurek.network.unpack(packed)
        expect_equal(type(unpacked), "table")
        expect_equal(type(unpacked.pos), "table")
        expect_equal(unpacked.pos.x, 10)
        expect_equal(unpacked.pos.y, 20)
        expect_equal(unpacked.tags[1], "a")
        expect_equal(unpacked.tags[2], "b")
    end)

    it("should produce compact binary (smaller than JSON)", function()
        local msg = { type = "move", x = 100.5, y = 200.5, id = 42 }
        local packed = lurek.network.pack(msg)
        -- MessagePack should be compact — well under 100 bytes for this
        expect_equal(#packed < 100, true)
    end)

    it("should error on invalid unpack data", function()
        expect_error(function()
            lurek.network.unpack("not valid msgpack \xff\xfe")
        end)
    end)
end)

test_summary()
