-- Canonical golden file for lurek.dsp evidence comparisons.

-- @describe golden: dsp evidence comparison
describe("golden: dsp evidence comparison", function()
    it("matches dsp evidence baselines", function()
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_bandpass_filtered.png", "tests/artifacts/baselines/dsp/dsp_bandpass_filtered.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_bandpass_source.png", "tests/artifacts/baselines/dsp/dsp_bandpass_source.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_fixture_spectrogram.png", "tests/artifacts/baselines/dsp/dsp_fixture_spectrogram.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_fixture_waveform.png", "tests/artifacts/baselines/dsp/dsp_fixture_waveform.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_highpass_filtered.png", "tests/artifacts/baselines/dsp/dsp_highpass_filtered.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_highpass_source.png", "tests/artifacts/baselines/dsp/dsp_highpass_source.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_lowpass_filtered.png", "tests/artifacts/baselines/dsp/dsp_lowpass_filtered.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_lowpass_source.png", "tests/artifacts/baselines/dsp/dsp_lowpass_source.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_normalized_peak_09.wav", "tests/artifacts/baselines/dsp/dsp_normalized_peak_09.wav")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_offline_lowpass_1khz.wav", "tests/artifacts/baselines/dsp/dsp_offline_lowpass_1khz.wav")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_waveform_sawtooth.png", "tests/artifacts/baselines/dsp/dsp_waveform_sawtooth.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_waveform_sine.png", "tests/artifacts/baselines/dsp/dsp_waveform_sine.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_waveform_square.png", "tests/artifacts/baselines/dsp/dsp_waveform_square.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_waveform_triangle.png", "tests/artifacts/baselines/dsp/dsp_waveform_triangle.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "dsp_waveform_white_noise.png", "tests/artifacts/baselines/dsp/dsp_waveform_white_noise.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "normalized.wav", "tests/artifacts/baselines/dsp/normalized.wav")
        expect_golden_file_match(evidence_output_dir("dsp") .. "offline_chain.wav", "tests/artifacts/baselines/dsp/offline_chain.wav")
        expect_golden_file_match(evidence_output_dir("dsp") .. "spectrogram.png", "tests/artifacts/baselines/dsp/spectrogram.png")
        expect_golden_file_match(evidence_output_dir("dsp") .. "waveform.png", "tests/artifacts/baselines/dsp/waveform.png")
    end)
end)
test_summary()
